In [2]:
import pandas as pd
import numpy as np
from mlxtend.frequent_patterns import apriori,association_rules, fpgrowth
# Apriori ==> frequent_patterns
# Association Rules ==> association_rules
#FPG growth ===> fpgrowth

In [7]:
# laod the dataset: 
df = pd.read_csv('market.csv', delimiter=';')
df.shape

(464, 22)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 464 entries, 0 to 463
Data columns (total 22 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Bread        464 non-null    int64
 1   Honey        464 non-null    int64
 2   Bacon        464 non-null    int64
 3   Toothpaste   464 non-null    int64
 4   Banana       464 non-null    int64
 5   Apple        464 non-null    int64
 6   Hazelnut     464 non-null    int64
 7   Cheese       464 non-null    int64
 8   Meat         464 non-null    int64
 9   Carrot       464 non-null    int64
 10  Cucumber     464 non-null    int64
 11  Onion        464 non-null    int64
 12  Milk         464 non-null    int64
 13  Butter       464 non-null    int64
 14  ShavingFoam  464 non-null    int64
 15  Salt         464 non-null    int64
 16  Flour        464 non-null    int64
 17  HeavyCream   464 non-null    int64
 18  Egg          464 non-null    int64
 19  Olive        464 non-null    int64
 20  Shampoo      464 non-null    int64
 21  Sugar        464 non-null    int64
dtypes: int64(22)
memory usage: 79.9 KB

In [9]:
df.head()

,Bread,Honey,Bacon,Toothpaste,Banana,Apple,Hazelnut,Cheese,Meat,Carrot,...,Milk,Butter,ShavingFoam,Salt,Flour,HeavyCream,Egg,Olive,Shampoo,Sugar
0,1,0,1,0,1,1,1,0,0,1,...,0,0,0,0,0,1,1,0,0,1
1,1,1,1,0,1,1,1,0,0,0,...,1,1,0,0,1,0,0,1,1,0
2,0,1,1,1,1,1,1,1,1,0,...,1,0,1,1,1,1,1,0,0,1
3,1,1,0,1,0,1,0,0,0,0,...,1,0,0,0,1,0,1,1,1,0
4,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# Only using Pandas (20):
# Calculate absolute support for each individual item, such as {Bread}, {Honey}
# Calculate relative support for each individual item

In [13]:
# Only using Pandas (20):
# Calculate absolute support for each individual item, such as {Bread}, {Honey}
# we can just count every item by summing the ones in every columns
absolute_support = df.sum()
absolute_support

Bread          189
Honey          193
Bacon          200
Toothpaste     178
Banana         208
Apple          188
Hazelnut       195
Cheese         206
Meat           180
Carrot         192
Cucumber       177
Onion          176
Milk           172
Butter         174
ShavingFoam    188
Salt           185
Flour          179
HeavyCream     193
Egg            187
Olive          177
Shampoo        170
Sugar          170
dtype: int64

In [16]:
# Calculate relative support for each individual item
# we can use the aboulate support divided by the number of transactions
relative_support = absolute_support / len(df)
relative_support

Bread          0.407328
Honey          0.415948
Bacon          0.431034
Toothpaste     0.383621
Banana         0.448276
Apple          0.405172
Hazelnut       0.420259
Cheese         0.443966
Meat           0.387931
Carrot         0.413793
Cucumber       0.381466
Onion          0.379310
Milk           0.370690
Butter         0.375000
ShavingFoam    0.405172
Salt           0.398707
Flour          0.385776
HeavyCream     0.415948
Egg            0.403017
Olive          0.381466
Shampoo        0.366379
Sugar          0.366379
dtype: float64

In [37]:
# Using Apriori (25)
# Create a dataframe with frequent itemsets
# Play with the min_sup parameter to see what happens. You will need a lower value to get good outputs.
# Check that the above relative support calculation is correct based on the Apriori df
apriori_df_1 = apriori(df, min_support= 0.5, use_colnames= True, max_len = None, verbose= 0, low_memory= False)
apriori_df_1

c:\Users\Student\Desktop\Abouhashem\nasaEnv\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

Empty DataFrame
Columns: [support, itemsets]
Index: []

In [80]:
# Using Apriori (25)
# Create a dataframe with frequent itemsets
# Play with the min_sup parameter to see what happens. You will need a lower value to get good outputs.
# Check that the above relative support calculation is correct based on the Apriori df
apriori_df_2 = apriori(df, min_support= 0.3, use_colnames= True, max_len = None, verbose= 0, low_memory= False)
apriori_df_2

c:\Users\Student\Desktop\Abouhashem\nasaEnv\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

     support       itemsets
0   0.407328        (Bread)
1   0.415948        (Honey)
2   0.431034        (Bacon)
3   0.383621   (Toothpaste)
4   0.448276       (Banana)
5   0.405172        (Apple)
6   0.420259     (Hazelnut)
7   0.443966       (Cheese)
8   0.387931         (Meat)
9   0.413793       (Carrot)
10  0.381466     (Cucumber)
11  0.379310        (Onion)
12  0.370690         (Milk)
13  0.375000       (Butter)
14  0.405172  (ShavingFoam)
15  0.398707         (Salt)
16  0.385776        (Flour)
17  0.415948   (HeavyCream)
18  0.403017          (Egg)
19  0.381466        (Olive)
20  0.366379      (Shampoo)
21  0.366379        (Sugar)

In [69]:

# Using Apriori (25)
# Create a dataframe with frequent itemsets
# Play with the min_sup parameter to see what happens. You will need a lower value to get good outputs.
# Check that the above relative support calculation is correct based on the Apriori df
apriori_df_2 = apriori(df, min_support= 0.1, use_colnames= True, max_len = None, verbose= 0, low_memory= False)
apriori_df_2

c:\Users\Student\Desktop\Abouhashem\nasaEnv\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

      support                       itemsets
0    0.407328                        (Bread)
1    0.415948                        (Honey)
2    0.431034                        (Bacon)
3    0.383621                   (Toothpaste)
4    0.448276                       (Banana)
..        ...                            ...
544  0.105603  (ShavingFoam, Cucumber, Salt)
545  0.101293      (Milk, HeavyCream, Onion)
546  0.105603     (ShavingFoam, Onion, Salt)
547  0.103448      (HeavyCream, Onion, Salt)
548  0.114224      (HeavyCream, Salt, Sugar)

[549 rows x 2 columns]

In [35]:
# Using FP-Growth (25)
# Create a dataframe with frequent itemsets
# Play with the min_sup parameter to see what happens. You will need a lower value to get good outputs.
# Check what is different with Apriori
fpgrowth_df_1 = fpgrowth(df, min_support= 0.5 , null_values= False, use_colnames= True, max_len= None, verbose= 0)  
fpgrowth_df_1

c:\Users\Student\Desktop\Abouhashem\nasaEnv\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

Empty DataFrame
Columns: [support, itemsets]
Index: []

In [70]:
# Using FP-Growth (25)
# Create a dataframe with frequent itemsets
# Play with the min_sup parameter to see what happens. You will need a lower value to get good outputs.
# Check what is different with Apriori
fpgrowth_df_2 = fpgrowth(df, min_support= 0.1 , null_values= False, use_colnames=True, max_len= None, verbose= 0)  
fpgrowth_df_2

c:\Users\Student\Desktop\Abouhashem\nasaEnv\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

      support                 itemsets
0    0.448276                 (Banana)
1    0.431034                  (Bacon)
2    0.420259               (Hazelnut)
3    0.415948             (HeavyCream)
4    0.413793                 (Carrot)
..        ...                      ...
544  0.105603    (Onion, Olive, Apple)
545  0.109914   (Banana, Onion, Olive)
546  0.114224  (Cheese, Onion, Carrot)
547  0.107759  (Banana, Onion, Carrot)
548  0.103448   (Onion, Carrot, Bacon)

[549 rows x 2 columns]

In [71]:
# Using association_rules on the above dataframes (30)
# Create association rules using the Apriori frequent itemset dataframe (minimum threshold of 0.01)
# Create association rules using the FP-Growth frequent itemset dataframe (minimum threshold of 0.01)

association_rules_apriori= association_rules(apriori_df_2 , 
    num_itemsets= len(df), 
    metric="confidence",   # You can also use "lift" or "support" based on your needs
    min_threshold=0.01, 
    null_values= False, 
    support_only= False, 
    )

association_rules_apriori

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Honey),(Bread),0.415948,0.407328,0.200431,0.481865,1.182992,1.0,0.031004,1.143858,0.264849,0.321799,0.125765,0.486964
1,(Bread),(Honey),0.407328,0.415948,0.200431,0.492063,1.182992,1.0,0.031004,1.149852,0.260997,0.321799,0.130323,0.486964
2,(Bacon),(Bread),0.431034,0.407328,0.202586,0.470000,1.153862,1.0,0.027014,1.118250,0.234365,0.318644,0.105745,0.483677
3,(Bread),(Bacon),0.407328,0.431034,0.202586,0.497354,1.153862,1.0,0.027014,1.131942,0.224990,0.318644,0.116562,0.483677
4,(Toothpaste),(Bread),0.383621,0.407328,0.174569,0.455056,1.117175,1.0,0.018310,1.087584,0.170163,0.283217,0.080531,0.441814
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2233,"(HeavyCream, Sugar)",(Salt),0.181034,0.398707,0.114224,0.630952,1.582497,1.0,0.042044,1.629310,0.449454,0.245370,0.386243,0.458719
2234,"(Sugar, Salt)",(HeavyCream),0.187500,0.415948,0.114224,0.609195,1.464594,1.0,0.036234,1.494485,0.390421,0.233480,0.330873,0.441903
2235,(HeavyCream),"(Sugar, Salt)",0.415948,0.187500,0.114224,0.274611,1.464594,1.0,0.036234,1.120089,0.543132,0.233480,0.107214,0.441903
2236,(Salt),"(HeavyCream, Sugar)",0.398707,0.181034,0.114224,0.286486,1.582497,1.0,0.042044,1.147793,0.612159,0.245370,0.128762,0.458719
2237,(Sugar),"(HeavyCream, Salt)",0.366379,0.206897,0.114224,0.311765,1.506863,1.0,0.038422,1.152373,0.530869,0.248826,0.132225,0.431924

In [56]:
association_rules_apriori

Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, representativity, leverage, conviction, zhangs_metric, jaccard, certainty, kulczynski]
Index: []

In [72]:
#Create association rules using the FP-Growth frequent itemset dataframe (minimum threshold of 0.01)
association_rules_fpgrowth= association_rules(fpgrowth_df_2  , 
    num_itemsets= len(df), 
    metric="confidence",   # You can also use "lift" or "support" based on your needs
    min_threshold=0.01, 
    null_values= False, 
    support_only= False, 
)
association_rules_fpgrowth

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Banana),(Bacon),0.448276,0.431034,0.241379,0.538462,1.249231,1.0,0.048157,1.232759,0.361607,0.378378,0.188811,0.549231
1,(Bacon),(Banana),0.431034,0.448276,0.241379,0.560000,1.249231,1.0,0.048157,1.253918,0.350649,0.378378,0.202500,0.549231
2,(Cheese),(Bacon),0.443966,0.431034,0.224138,0.504854,1.171262,1.0,0.032773,1.149087,0.262970,0.344371,0.129744,0.512427
3,(Bacon),(Cheese),0.431034,0.443966,0.224138,0.520000,1.171262,1.0,0.032773,1.158405,0.256993,0.344371,0.136744,0.512427
4,"(Banana, Cheese)",(Bacon),0.224138,0.431034,0.140086,0.625000,1.450000,1.0,0.043475,1.517241,0.400000,0.271967,0.340909,0.475000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2233,"(Onion, Bacon)",(Carrot),0.187500,0.413793,0.103448,0.551724,1.333333,1.0,0.025862,1.307692,0.307692,0.207792,0.235294,0.400862
2234,"(Carrot, Bacon)",(Onion),0.198276,0.379310,0.103448,0.521739,1.375494,1.0,0.028240,1.297806,0.340502,0.218182,0.229469,0.397233
2235,(Onion),"(Carrot, Bacon)",0.379310,0.198276,0.103448,0.272727,1.375494,1.0,0.028240,1.102371,0.439815,0.218182,0.092864,0.397233
2236,(Carrot),"(Onion, Bacon)",0.413793,0.187500,0.103448,0.250000,1.333333,1.0,0.025862,1.083333,0.426471,0.207792,0.076923,0.400862
2237,(Bacon),"(Onion, Carrot)",0.431034,0.183190,0.103448,0.240000,1.310118,1.0,0.024487,1.074750,0.416035,0.202532,0.069551,0.402353

In [73]:
for _, row in association_rules_apriori.iterrows():
    print(f"{row['antecedents']} => {row['consequents']} "
          f"[{row['support']:.2f}, {row['confidence']:.2f}, {row['lift']:.2f}]")

frozenset({'Honey'}) => frozenset({'Bread'}) [0.20, 0.48, 1.18]
frozenset({'Bread'}) => frozenset({'Honey'}) [0.20, 0.49, 1.18]
frozenset({'Bacon'}) => frozenset({'Bread'}) [0.20, 0.47, 1.15]
frozenset({'Bread'}) => frozenset({'Bacon'}) [0.20, 0.50, 1.15]
frozenset({'Toothpaste'}) => frozenset({'Bread'}) [0.17, 0.46, 1.12]
frozenset({'Bread'}) => frozenset({'Toothpaste'}) [0.17, 0.43, 1.12]
frozenset({'Banana'}) => frozenset({'Bread'}) [0.21, 0.47, 1.16]
frozenset({'Bread'}) => frozenset({'Banana'}) [0.21, 0.52, 1.16]
frozenset({'Apple'}) => frozenset({'Bread'}) [0.17, 0.43, 1.06]
frozenset({'Bread'}) => frozenset({'Apple'}) [0.17, 0.43, 1.06]
frozenset({'Hazelnut'}) => frozenset({'Bread'}) [0.19, 0.45, 1.10]
frozenset({'Bread'}) => frozenset({'Hazelnut'}) [0.19, 0.46, 1.10]
frozenset({'Cheese'}) => frozenset({'Bread'}) [0.22, 0.49, 1.19]
frozenset({'Bread'}) => frozenset({'Cheese'}) [0.22, 0.53, 1.19]
frozenset({'Meat'}) => frozenset({'Bread'}) [0.17, 0.44, 1.08]
frozenset({'Bread'}) => frozenset({'Meat'}) [0.17, 0.42, 1.08]
frozenset({'Carrot'}) => frozenset({'Bread'}) [0.19, 0.47, 1.15]
frozenset({'Bread'}) => frozenset({'Carrot'}) [0.19, 0.48, 1.15]
frozenset({'Cucumber'}) => frozenset({'Bread'}) [0.16, 0.43, 1.05]
frozenset({'Bread'}) => frozenset({'Cucumber'}) [0.16, 0.40, 1.05]
frozenset({'Onion'}) => frozenset({'Bread'}) [0.17, 0.44, 1.07]
frozenset({'Bread'}) => frozenset({'Onion'}) [0.17, 0.41, 1.07]
frozenset({'Milk'}) => frozenset({'Bread'}) [0.18, 0.48, 1.17]
frozenset({'Bread'}) => frozenset({'Milk'}) [0.18, 0.43, 1.17]
frozenset({'Butter'}) => frozenset({'Bread'}) [0.20, 0.52, 1.28]
frozenset({'Bread'}) => frozenset({'Butter'}) [0.20, 0.48, 1.28]
frozenset({'ShavingFoam'}) => frozenset({'Bread'}) [0.19, 0.46, 1.12]
frozenset({'Bread'}) => frozenset({'ShavingFoam'}) [0.19, 0.46, 1.12]
frozenset({'Salt'}) => frozenset({'Bread'}) [0.21, 0.52, 1.27]
frozenset({'Bread'}) => frozenset({'Salt'}) [0.21, 0.51, 1.27]
frozenset({'Flour'}) => frozenset({'Bread'}) [0.17, 0.45, 1.10]
frozenset({'Bread'}) => frozenset({'Flour'}) [0.17, 0.42, 1.10]
frozenset({'HeavyCream'}) => frozenset({'Bread'}) [0.19, 0.45, 1.11]
frozenset({'Bread'}) => frozenset({'HeavyCream'}) [0.19, 0.46, 1.11]
frozenset({'Egg'}) => frozenset({'Bread'}) [0.19, 0.46, 1.13]
frozenset({'Bread'}) => frozenset({'Egg'}) [0.19, 0.46, 1.13]
frozenset({'Olive'}) => frozenset({'Bread'}) [0.17, 0.45, 1.10]
frozenset({'Bread'}) => frozenset({'Olive'}) [0.17, 0.42, 1.10]
frozenset({'Shampoo'}) => frozenset({'Bread'}) [0.17, 0.47, 1.16]
frozenset({'Bread'}) => frozenset({'Shampoo'}) [0.17, 0.42, 1.16]
frozenset({'Sugar'}) => frozenset({'Bread'}) [0.17, 0.48, 1.17]
frozenset({'Bread'}) => frozenset({'Sugar'}) [0.17, 0.43, 1.17]
frozenset({'Bacon'}) => frozenset({'Honey'}) [0.20, 0.47, 1.13]
frozenset({'Honey'}) => frozenset({'Bacon'}) [0.20, 0.49, 1.13]
frozenset({'Toothpaste'}) => frozenset({'Honey'}) [0.18, 0.47, 1.13]
frozenset({'Honey'}) => frozenset({'Toothpaste'}) [0.18, 0.44, 1.13]
frozenset({'Banana'}) => frozenset({'Honey'}) [0.21, 0.48, 1.14]
frozenset({'Honey'}) => frozenset({'Banana'}) [0.21, 0.51, 1.14]
frozenset({'Apple'}) => frozenset({'Honey'}) [0.19, 0.46, 1.11]
frozenset({'Honey'}) => frozenset({'Apple'}) [0.19, 0.45, 1.11]
frozenset({'Hazelnut'}) => frozenset({'Honey'}) [0.19, 0.46, 1.10]
frozenset({'Honey'}) => frozenset({'Hazelnut'}) [0.19, 0.46, 1.10]
frozenset({'Cheese'}) => frozenset({'Honey'}) [0.22, 0.49, 1.18]
frozenset({'Honey'}) => frozenset({'Cheese'}) [0.22, 0.52, 1.18]
frozenset({'Meat'}) => frozenset({'Honey'}) [0.20, 0.52, 1.26]
frozenset({'Honey'}) => frozenset({'Meat'}) [0.20, 0.49, 1.26]
frozenset({'Carrot'}) => frozenset({'Honey'}) [0.20, 0.49, 1.19]
frozenset({'Honey'}) => frozenset({'Carrot'}) [0.20, 0.49, 1.19]
frozenset({'Cucumber'}) => frozenset({'Honey'}) [0.17, 0.44, 1.05]
frozenset({'Honey'}) => frozenset({'Cucumber'}) [0.17, 0.40, 1.05]
frozenset({'Onion'}) => frozenset({'Honey'}) [0.18, 0.47, 1.12]
frozenset({'Honey'}) => frozenset({'Onion'}) [0.18, 0.42, 1.12]
frozenset({'Milk'}) => frozenset({'Honey'}) [0.17, 0.47, 1.13]
frozenset({'Honey'}) => frozenset({'Milk'}) [0.17, 0.42, 1.13]
frozenset({'Butter'}) => frozenset({'Honey'}) [0.19, 0.49, 1.19]
frozenset({'Honey'}) => frozenset({'Butter'}) [0.19, 0.45, 1.19]
frozenset({'ShavingFoam'}) => frozenset({'Honey'}) [0.19, 0.46, 1.11]
frozenset({'Honey'}) => frozenset({'ShavingFoam'}) [0.19, 0.45, 1.11]
frozenset({'Salt'}) => frozenset({'Honey'}) [0.17, 0.42, 1.01]
frozenset({'Honey'}) => frozenset({'Salt'}) [0.17, 0.40, 1.01]
frozenset({'Flour'}) => frozenset({'Honey'}) [0.17, 0.44, 1.05]
frozenset({'Honey'}) => frozenset({'Flour'}) [0.17, 0.40, 1.05]
frozenset({'HeavyCream'}) => frozenset({'Honey'}) [0.20, 0.49, 1.18]
frozenset({'Honey'}) => frozenset({'HeavyCream'}) [0.20, 0.49, 1.18]
frozenset({'Egg'}) => frozenset({'Honey'}) [0.21, 0.52, 1.25]
frozenset({'Honey'}) => frozenset({'Egg'}) [0.21, 0.50, 1.25]
frozenset({'Olive'}) => frozenset({'Honey'}) [0.16, 0.42, 1.01]
frozenset({'Honey'}) => frozenset({'Olive'}) [0.16, 0.38, 1.01]
frozenset({'Shampoo'}) => frozenset({'Honey'}) [0.19, 0.51, 1.23]
frozenset({'Honey'}) => frozenset({'Shampoo'}) [0.19, 0.45, 1.23]
frozenset({'Sugar'}) => frozenset({'Honey'}) [0.17, 0.47, 1.13]
frozenset({'Honey'}) => frozenset({'Sugar'}) [0.17, 0.41, 1.13]
frozenset({'Toothpaste'}) => frozenset({'Bacon'}) [0.17, 0.46, 1.06]
frozenset({'Bacon'}) => frozenset({'Toothpaste'}) [0.17, 0.41, 1.06]
frozenset({'Banana'}) => frozenset({'Bacon'}) [0.24, 0.54, 1.25]
frozenset({'Bacon'}) => frozenset({'Banana'}) [0.24, 0.56, 1.25]
frozenset({'Apple'}) => frozenset({'Bacon'}) [0.19, 0.46, 1.07]
frozenset({'Bacon'}) => frozenset({'Apple'}) [0.19, 0.43, 1.07]
frozenset({'Hazelnut'}) => frozenset({'Bacon'}) [0.22, 0.53, 1.23]
frozenset({'Bacon'}) => frozenset({'Hazelnut'}) [0.22, 0.52, 1.23]
frozenset({'Cheese'}) => frozenset({'Bacon'}) [0.22, 0.50, 1.17]
frozenset({'Bacon'}) => frozenset({'Cheese'}) [0.22, 0.52, 1.17]
frozenset({'Meat'}) => frozenset({'Bacon'}) [0.22, 0.56, 1.29]
frozenset({'Bacon'}) => frozenset({'Meat'}) [0.22, 0.50, 1.29]
frozenset({'Carrot'}) => frozenset({'Bacon'}) [0.20, 0.48, 1.11]
frozenset({'Bacon'}) => frozenset({'Carrot'}) [0.20, 0.46, 1.11]
frozenset({'Cucumber'}) => frozenset({'Bacon'}) [0.18, 0.48, 1.11]
frozenset({'Bacon'}) => frozenset({'Cucumber'}) [0.18, 0.42, 1.11]
frozenset({'Onion'}) => frozenset({'Bacon'}) [0.19, 0.49, 1.15]
frozenset({'Bacon'}) => frozenset({'Onion'}) [0.19, 0.43, 1.15]
frozenset({'Milk'}) => frozenset({'Bacon'}) [0.19, 0.51, 1.17]
frozenset({'Bacon'}) => frozenset({'Milk'}) [0.19, 0.43, 1.17]
frozenset({'Bacon'}) => frozenset({'Butter'}) [0.21, 0.48, 1.28]
frozenset({'Butter'}) => frozenset({'Bacon'}) [0.21, 0.55, 1.28]
frozenset({'ShavingFoam'}) => frozenset({'Bacon'}) [0.22, 0.53, 1.23]
frozenset({'Bacon'}) => frozenset({'ShavingFoam'}) [0.22, 0.50, 1.23]
frozenset({'Salt'}) => frozenset({'Bacon'}) [0.17, 0.42, 0.98]
frozenset({'Bacon'}) => frozenset({'Salt'}) [0.17, 0.39, 0.98]
frozenset({'Flour'}) => frozenset({'Bacon'}) [0.17, 0.43, 1.00]
frozenset({'Bacon'}) => frozenset({'Flour'}) [0.17, 0.39, 1.00]
frozenset({'HeavyCream'}) => frozenset({'Bacon'}) [0.20, 0.48, 1.12]
frozenset({'Bacon'}) => frozenset({'HeavyCream'}) [0.20, 0.47, 1.12]
frozenset({'Egg'}) => frozenset({'Bacon'}) [0.20, 0.50, 1.17]
frozenset({'Bacon'}) => frozenset({'Egg'}) [0.20, 0.47, 1.17]
frozenset({'Olive'}) => frozenset({'Bacon'}) [0.18, 0.47, 1.09]
frozenset({'Bacon'}) => frozenset({'Olive'}) [0.18, 0.41, 1.09]
frozenset({'Bacon'}) => frozenset({'Shampoo'}) [0.17, 0.39, 1.05]
frozenset({'Shampoo'}) => frozenset({'Bacon'}) [0.17, 0.45, 1.05]
frozenset({'Sugar'}) => frozenset({'Bacon'}) [0.19, 0.51, 1.19]
frozenset({'Bacon'}) => frozenset({'Sugar'}) [0.19, 0.43, 1.19]
frozenset({'Banana'}) => frozenset({'Toothpaste'}) [0.20, 0.45, 1.18]
frozenset({'Toothpaste'}) => frozenset({'Banana'}) [0.20, 0.53, 1.18]
frozenset({'Toothpaste'}) => frozenset({'Apple'}) [0.18, 0.47, 1.16]
frozenset({'Apple'}) => frozenset({'Toothpaste'}) [0.18, 0.45, 1.16]
frozenset({'Hazelnut'}) => frozenset({'Toothpaste'}) [0.20, 0.48, 1.26]
frozenset({'Toothpaste'}) => frozenset({'Hazelnut'}) [0.20, 0.53, 1.26]
frozenset({'Cheese'}) => frozenset({'Toothpaste'}) [0.20, 0.45, 1.16]
frozenset({'Toothpaste'}) => frozenset({'Cheese'}) [0.20, 0.52, 1.16]
frozenset({'Toothpaste'}) => frozenset({'Meat'}) [0.17, 0.44, 1.13]
frozenset({'Meat'}) => frozenset({'Toothpaste'}) [0.17, 0.43, 1.13]
frozenset({'Toothpaste'}) => frozenset({'Carrot'}) [0.20, 0.53, 1.29]
frozenset({'Carrot'}) => frozenset({'Toothpaste'}) [0.20, 0.49, 1.29]
frozenset({'Toothpaste'}) => frozenset({'Cucumber'}) [0.17, 0.45, 1.18]
frozenset({'Cucumber'}) => frozenset({'Toothpaste'}) [0.17, 0.45, 1.18]
frozenset({'Toothpaste'}) => frozenset({'Onion'}) [0.19, 0.51, 1.33]
frozenset({'Onion'}) => frozenset({'Toothpaste'}) [0.19, 0.51, 1.33]
frozenset({'Toothpaste'}) => frozenset({'Milk'}) [0.18, 0.46, 1.24]
frozenset({'Milk'}) => frozenset({'Toothpaste'}) [0.18, 0.48, 1.24]
frozenset({'Toothpaste'}) => frozenset({'Butter'}) [0.18, 0.47, 1.26]
frozenset({'Butter'}) => frozenset({'Toothpaste'}) [0.18, 0.48, 1.26]
frozenset({'ShavingFoam'}) => frozenset({'Toothpaste'}) [0.19, 0.46, 1.21]
frozenset({'Toothpaste'}) => frozenset({'ShavingFoam'}) [0.19, 0.49, 1.21]
frozenset({'Toothpaste'}) => frozenset({'Salt'}) [0.19, 0.51, 1.27]
frozenset({'Salt'}) => frozenset({'Toothpaste'}) [0.19, 0.49, 1.27]
frozenset({'Flour'}) => frozenset({'Toothpaste'}) [0.18, 0.47, 1.24]
frozenset({'Toothpaste'}) => frozenset({'Flour'}) [0.18, 0.48, 1.24]
frozenset({'Toothpaste'}) => frozenset({'HeavyCream'}) [0.19, 0.50, 1.20]
frozenset({'HeavyCream'}) => frozenset({'Toothpaste'}) [0.19, 0.46, 1.20]
frozenset({'Egg'}) => frozenset({'Toothpaste'}) [0.18, 0.45, 1.17]
frozenset({'Toothpaste'}) => frozenset({'Egg'}) [0.18, 0.47, 1.17]
frozenset({'Toothpaste'}) => frozenset({'Olive'}) [0.17, 0.44, 1.16]
frozenset({'Olive'}) => frozenset({'Toothpaste'}) [0.17, 0.45, 1.16]
frozenset({'Toothpaste'}) => frozenset({'Shampoo'}) [0.15, 0.38, 1.04]
frozenset({'Shampoo'}) => frozenset({'Toothpaste'}) [0.15, 0.40, 1.04]
frozenset({'Toothpaste'}) => frozenset({'Sugar'}) [0.17, 0.46, 1.24]
frozenset({'Sugar'}) => frozenset({'Toothpaste'}) [0.17, 0.48, 1.24]
frozenset({'Banana'}) => frozenset({'Apple'}) [0.22, 0.49, 1.21]
frozenset({'Apple'}) => frozenset({'Banana'}) [0.22, 0.54, 1.21]
frozenset({'Banana'}) => frozenset({'Hazelnut'}) [0.22, 0.50, 1.18]
frozenset({'Hazelnut'}) => frozenset({'Banana'}) [0.22, 0.53, 1.18]
frozenset({'Banana'}) => frozenset({'Cheese'}) [0.22, 0.50, 1.13]
frozenset({'Cheese'}) => frozenset({'Banana'}) [0.22, 0.50, 1.13]
frozenset({'Banana'}) => frozenset({'Meat'}) [0.19, 0.43, 1.10]
frozenset({'Meat'}) => frozenset({'Banana'}) [0.19, 0.49, 1.10]
frozenset({'Banana'}) => frozenset({'Carrot'}) [0.22, 0.49, 1.19]
frozenset({'Carrot'}) => frozenset({'Banana'}) [0.22, 0.53, 1.19]
frozenset({'Banana'}) => frozenset({'Cucumber'}) [0.20, 0.44, 1.15]
frozenset({'Cucumber'}) => frozenset({'Banana'}) [0.20, 0.51, 1.15]
frozenset({'Banana'}) => frozenset({'Onion'}) [0.21, 0.47, 1.23]
frozenset({'Onion'}) => frozenset({'Banana'}) [0.21, 0.55, 1.23]
frozenset({'Banana'}) => frozenset({'Milk'}) [0.18, 0.40, 1.09]
frozenset({'Milk'}) => frozenset({'Banana'}) [0.18, 0.49, 1.09]
frozenset({'Banana'}) => frozenset({'Butter'}) [0.18, 0.40, 1.06]
frozenset({'Butter'}) => frozenset({'Banana'}) [0.18, 0.48, 1.06]
frozenset({'Banana'}) => frozenset({'ShavingFoam'}) [0.22, 0.49, 1.21]
frozenset({'ShavingFoam'}) => frozenset({'Banana'}) [0.22, 0.54, 1.21]
frozenset({'Banana'}) => frozenset({'Salt'}) [0.19, 0.43, 1.09]
frozenset({'Salt'}) => frozenset({'Banana'}) [0.19, 0.49, 1.09]
frozenset({'Flour'}) => frozenset({'Banana'}) [0.19, 0.48, 1.07]
frozenset({'Banana'}) => frozenset({'Flour'}) [0.19, 0.41, 1.07]
frozenset({'Banana'}) => frozenset({'HeavyCream'}) [0.20, 0.44, 1.05]
frozenset({'HeavyCream'}) => frozenset({'Banana'}) [0.20, 0.47, 1.05]
frozenset({'Banana'}) => frozenset({'Egg'}) [0.21, 0.48, 1.18]
frozenset({'Egg'}) => frozenset({'Banana'}) [0.21, 0.53, 1.18]
frozenset({'Banana'}) => frozenset({'Olive'}) [0.20, 0.46, 1.20]
frozenset({'Olive'}) => frozenset({'Banana'}) [0.20, 0.54, 1.20]
frozenset({'Banana'}) => frozenset({'Shampoo'}) [0.18, 0.40, 1.09]
frozenset({'Shampoo'}) => frozenset({'Banana'}) [0.18, 0.49, 1.09]
frozenset({'Banana'}) => frozenset({'Sugar'}) [0.18, 0.39, 1.08]
frozenset({'Sugar'}) => frozenset({'Banana'}) [0.18, 0.48, 1.08]
frozenset({'Hazelnut'}) => frozenset({'Apple'}) [0.17, 0.41, 1.00]
frozenset({'Apple'}) => frozenset({'Hazelnut'}) [0.17, 0.42, 1.00]
frozenset({'Cheese'}) => frozenset({'Apple'}) [0.18, 0.41, 1.02]
frozenset({'Apple'}) => frozenset({'Cheese'}) [0.18, 0.45, 1.02]
frozenset({'Meat'}) => frozenset({'Apple'}) [0.19, 0.49, 1.22]
frozenset({'Apple'}) => frozenset({'Meat'}) [0.19, 0.47, 1.22]
frozenset({'Apple'}) => frozenset({'Carrot'}) [0.19, 0.47, 1.13]
frozenset({'Carrot'}) => frozenset({'Apple'}) [0.19, 0.46, 1.13]
frozenset({'Cucumber'}) => frozenset({'Apple'}) [0.16, 0.41, 1.02]
frozenset({'Apple'}) => frozenset({'Cucumber'}) [0.16, 0.39, 1.02]
frozenset({'Onion'}) => frozenset({'Apple'}) [0.18, 0.48, 1.19]
frozenset({'Apple'}) => frozenset({'Onion'}) [0.18, 0.45, 1.19]
frozenset({'Milk'}) => frozenset({'Apple'}) [0.16, 0.44, 1.08]
frozenset({'Apple'}) => frozenset({'Milk'}) [0.16, 0.40, 1.08]
frozenset({'Apple'}) => frozenset({'Butter'}) [0.18, 0.44, 1.16]
frozenset({'Butter'}) => frozenset({'Apple'}) [0.18, 0.47, 1.16]
frozenset({'ShavingFoam'}) => frozenset({'Apple'}) [0.18, 0.45, 1.12]
frozenset({'Apple'}) => frozenset({'ShavingFoam'}) [0.18, 0.45, 1.12]
frozenset({'Salt'}) => frozenset({'Apple'}) [0.18, 0.45, 1.12]
frozenset({'Apple'}) => frozenset({'Salt'}) [0.18, 0.45, 1.12]
frozenset({'Flour'}) => frozenset({'Apple'}) [0.17, 0.44, 1.08]
frozenset({'Apple'}) => frozenset({'Flour'}) [0.17, 0.41, 1.08]
frozenset({'HeavyCream'}) => frozenset({'Apple'}) [0.20, 0.48, 1.18]
frozenset({'Apple'}) => frozenset({'HeavyCream'}) [0.20, 0.49, 1.18]
frozenset({'Egg'}) => frozenset({'Apple'}) [0.20, 0.49, 1.20]
frozenset({'Apple'}) => frozenset({'Egg'}) [0.20, 0.48, 1.20]
frozenset({'Olive'}) => frozenset({'Apple'}) [0.19, 0.49, 1.21]
frozenset({'Apple'}) => frozenset({'Olive'}) [0.19, 0.46, 1.21]
frozenset({'Apple'}) => frozenset({'Shampoo'}) [0.17, 0.43, 1.16]
frozenset({'Shampoo'}) => frozenset({'Apple'}) [0.17, 0.47, 1.16]
frozenset({'Apple'}) => frozenset({'Sugar'}) [0.16, 0.40, 1.09]
frozenset({'Sugar'}) => frozenset({'Apple'}) [0.16, 0.44, 1.09]
frozenset({'Cheese'}) => frozenset({'Hazelnut'}) [0.21, 0.47, 1.11]
frozenset({'Hazelnut'}) => frozenset({'Cheese'}) [0.21, 0.49, 1.11]
frozenset({'Hazelnut'}) => frozenset({'Meat'}) [0.19, 0.46, 1.18]
frozenset({'Meat'}) => frozenset({'Hazelnut'}) [0.19, 0.49, 1.18]
frozenset({'Hazelnut'}) => frozenset({'Carrot'}) [0.18, 0.44, 1.05]
frozenset({'Carrot'}) => frozenset({'Hazelnut'}) [0.18, 0.44, 1.05]
frozenset({'Hazelnut'}) => frozenset({'Cucumber'}) [0.19, 0.45, 1.18]
frozenset({'Cucumber'}) => frozenset({'Hazelnut'}) [0.19, 0.50, 1.18]
frozenset({'Hazelnut'}) => frozenset({'Onion'}) [0.18, 0.43, 1.14]
frozenset({'Onion'}) => frozenset({'Hazelnut'}) [0.18, 0.48, 1.14]
frozenset({'Hazelnut'}) => frozenset({'Milk'}) [0.18, 0.43, 1.16]
frozenset({'Milk'}) => frozenset({'Hazelnut'}) [0.18, 0.49, 1.16]
frozenset({'Hazelnut'}) => frozenset({'Butter'}) [0.20, 0.47, 1.26]
frozenset({'Butter'}) => frozenset({'Hazelnut'}) [0.20, 0.53, 1.26]
frozenset({'ShavingFoam'}) => frozenset({'Hazelnut'}) [0.19, 0.47, 1.13]
frozenset({'Hazelnut'}) => frozenset({'ShavingFoam'}) [0.19, 0.46, 1.13]
frozenset({'Hazelnut'}) => frozenset({'Salt'}) [0.18, 0.44, 1.09]
frozenset({'Salt'}) => frozenset({'Hazelnut'}) [0.18, 0.46, 1.09]
frozenset({'Flour'}) => frozenset({'Hazelnut'}) [0.20, 0.52, 1.24]
frozenset({'Hazelnut'}) => frozenset({'Flour'}) [0.20, 0.48, 1.24]
frozenset({'Hazelnut'}) => frozenset({'HeavyCream'}) [0.21, 0.50, 1.20]
frozenset({'HeavyCream'}) => frozenset({'Hazelnut'}) [0.21, 0.50, 1.20]
frozenset({'Hazelnut'}) => frozenset({'Egg'}) [0.20, 0.47, 1.16]
frozenset({'Egg'}) => frozenset({'Hazelnut'}) [0.20, 0.49, 1.16]
frozenset({'Hazelnut'}) => frozenset({'Olive'}) [0.18, 0.43, 1.12]
frozenset({'Olive'}) => frozenset({'Hazelnut'}) [0.18, 0.47, 1.12]
frozenset({'Hazelnut'}) => frozenset({'Shampoo'}) [0.17, 0.42, 1.13]
frozenset({'Shampoo'}) => frozenset({'Hazelnut'}) [0.17, 0.48, 1.13]
frozenset({'Hazelnut'}) => frozenset({'Sugar'}) [0.18, 0.43, 1.18]
frozenset({'Sugar'}) => frozenset({'Hazelnut'}) [0.18, 0.49, 1.18]
frozenset({'Cheese'}) => frozenset({'Meat'}) [0.20, 0.46, 1.19]
frozenset({'Meat'}) => frozenset({'Cheese'}) [0.20, 0.53, 1.19]
frozenset({'Cheese'}) => frozenset({'Carrot'}) [0.22, 0.49, 1.18]
frozenset({'Carrot'}) => frozenset({'Cheese'}) [0.22, 0.53, 1.18]
frozenset({'Cheese'}) => frozenset({'Cucumber'}) [0.19, 0.43, 1.13]
frozenset({'Cucumber'}) => frozenset({'Cheese'}) [0.19, 0.50, 1.13]
frozenset({'Cheese'}) => frozenset({'Onion'}) [0.19, 0.43, 1.14]
frozenset({'Onion'}) => frozenset({'Cheese'}) [0.19, 0.51, 1.14]
frozenset({'Cheese'}) => frozenset({'Milk'}) [0.18, 0.40, 1.09]
frozenset({'Milk'}) => frozenset({'Cheese'}) [0.18, 0.48, 1.09]
frozenset({'Cheese'}) => frozenset({'Butter'}) [0.22, 0.49, 1.29]
frozenset({'Butter'}) => frozenset({'Cheese'}) [0.22, 0.57, 1.29]
frozenset({'ShavingFoam'}) => frozenset({'Cheese'}) [0.21, 0.53, 1.19]
frozenset({'Cheese'}) => frozenset({'ShavingFoam'}) [0.21, 0.48, 1.19]
frozenset({'Cheese'}) => frozenset({'Salt'}) [0.20, 0.45, 1.13]
frozenset({'Salt'}) => frozenset({'Cheese'}) [0.20, 0.50, 1.13]
frozenset({'Flour'}) => frozenset({'Cheese'}) [0.19, 0.49, 1.11]
frozenset({'Cheese'}) => frozenset({'Flour'}) [0.19, 0.43, 1.11]
frozenset({'Cheese'}) => frozenset({'HeavyCream'}) [0.20, 0.45, 1.09]
frozenset({'HeavyCream'}) => frozenset({'Cheese'}) [0.20, 0.48, 1.09]
frozenset({'Cheese'}) => frozenset({'Egg'}) [0.22, 0.50, 1.24]
frozenset({'Egg'}) => frozenset({'Cheese'}) [0.22, 0.55, 1.24]
frozenset({'Cheese'}) => frozenset({'Olive'}) [0.17, 0.38, 1.01]
frozenset({'Olive'}) => frozenset({'Cheese'}) [0.17, 0.45, 1.01]
frozenset({'Cheese'}) => frozenset({'Shampoo'}) [0.19, 0.42, 1.15]
frozenset({'Shampoo'}) => frozenset({'Cheese'}) [0.19, 0.51, 1.15]
frozenset({'Cheese'}) => frozenset({'Sugar'}) [0.19, 0.42, 1.15]
frozenset({'Sugar'}) => frozenset({'Cheese'}) [0.19, 0.51, 1.15]
frozenset({'Meat'}) => frozenset({'Carrot'}) [0.17, 0.43, 1.05]
frozenset({'Carrot'}) => frozenset({'Meat'}) [0.17, 0.41, 1.05]
frozenset({'Meat'}) => frozenset({'Cucumber'}) [0.17, 0.43, 1.12]
frozenset({'Cucumber'}) => frozenset({'Meat'}) [0.17, 0.44, 1.12]
frozenset({'Meat'}) => frozenset({'Onion'}) [0.18, 0.46, 1.22]
frozenset({'Onion'}) => frozenset({'Meat'}) [0.18, 0.47, 1.22]
frozenset({'Milk'}) => frozenset({'Meat'}) [0.15, 0.41, 1.06]
frozenset({'Meat'}) => frozenset({'Milk'}) [0.15, 0.39, 1.06]
frozenset({'Meat'}) => frozenset({'Butter'}) [0.16, 0.42, 1.13]
frozenset({'Butter'}) => frozenset({'Meat'}) [0.16, 0.44, 1.13]
frozenset({'ShavingFoam'}) => frozenset({'Meat'}) [0.18, 0.45, 1.17]
frozenset({'Meat'}) => frozenset({'ShavingFoam'}) [0.18, 0.47, 1.17]
frozenset({'Meat'}) => frozenset({'Salt'}) [0.17, 0.45, 1.13]
frozenset({'Salt'}) => frozenset({'Meat'}) [0.17, 0.44, 1.13]
frozenset({'Flour'}) => frozenset({'Meat'}) [0.15, 0.39, 0.99]
frozenset({'Meat'}) => frozenset({'Flour'}) [0.15, 0.38, 0.99]
frozenset({'Meat'}) => frozenset({'HeavyCream'}) [0.19, 0.50, 1.20]
frozenset({'HeavyCream'}) => frozenset({'Meat'}) [0.19, 0.47, 1.20]
frozenset({'Egg'}) => frozenset({'Meat'}) [0.19, 0.46, 1.19]
frozenset({'Meat'}) => frozenset({'Egg'}) [0.19, 0.48, 1.19]
frozenset({'Meat'}) => frozenset({'Olive'}) [0.17, 0.44, 1.15]
frozenset({'Olive'}) => frozenset({'Meat'}) [0.17, 0.45, 1.15]

In [74]:
def imbalance_ratio(support_a, support_b, support_ab):
    numerator = abs(support_a - support_b)
    denominator = support_a + support_b - support_ab

    return numerator / denominator

In [76]:
association_rules_apriori['imbalance ratio'] = association_rules_apriori.apply(
    lambda row: imbalance_ratio(
        row['antecedent support'],
        row['consequent support'],
        row['support']
    ),
    axis=1
)

association_rules_apriori.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski,imbalance ratio
0,(Honey),(Bread),0.415948,0.407328,0.200431,0.481865,1.182992,1.0,0.031004,1.143858,0.264849,0.321799,0.125765,0.486964,0.013841
1,(Bread),(Honey),0.407328,0.415948,0.200431,0.492063,1.182992,1.0,0.031004,1.149852,0.260997,0.321799,0.130323,0.486964,0.013841
2,(Bacon),(Bread),0.431034,0.407328,0.202586,0.470000,1.153862,1.0,0.027014,1.118250,0.234365,0.318644,0.105745,0.483677,0.037288
3,(Bread),(Bacon),0.407328,0.431034,0.202586,0.497354,1.153862,1.0,0.027014,1.131942,0.224990,0.318644,0.116562,0.483677,0.037288
4,(Toothpaste),(Bread),0.383621,0.407328,0.174569,0.455056,1.117175,1.0,0.018310,1.087584,0.170163,0.283217,0.080531,0.441814,0.038462

In [77]:
association_rules_fpgrowth['imbalance ratio'] = association_rules_fpgrowth.apply(
    lambda row: imbalance_ratio(
        row['antecedent support'],
        row['consequent support'],
        row['support']
    ),
    axis=1
)

association_rules_fpgrowth.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski,imbalance ratio
0,(Banana),(Bacon),0.448276,0.431034,0.241379,0.538462,1.249231,1.0,0.048157,1.232759,0.361607,0.378378,0.188811,0.549231,0.027027
1,(Bacon),(Banana),0.431034,0.448276,0.241379,0.560000,1.249231,1.0,0.048157,1.253918,0.350649,0.378378,0.202500,0.549231,0.027027
2,(Cheese),(Bacon),0.443966,0.431034,0.224138,0.504854,1.171262,1.0,0.032773,1.149087,0.262970,0.344371,0.129744,0.512427,0.019868
3,(Bacon),(Cheese),0.431034,0.443966,0.224138,0.520000,1.171262,1.0,0.032773,1.158405,0.256993,0.344371,0.136744,0.512427,0.019868
4,"(Banana, Cheese)",(Bacon),0.224138,0.431034,0.140086,0.625000,1.450000,1.0,0.043475,1.517241,0.400000,0.271967,0.340909,0.475000,0.401674

In [78]:
for _, row in association_rules_apriori.iterrows():
    print(f"{row['antecedents']} => {row['consequents']} "
          f"[{row['kulczynski']:.2f}, {row['imbalance ratio']:.2f}]")

frozenset({'Honey'}) => frozenset({'Bread'}) [0.49, 0.01]
frozenset({'Bread'}) => frozenset({'Honey'}) [0.49, 0.01]
frozenset({'Bacon'}) => frozenset({'Bread'}) [0.48, 0.04]
frozenset({'Bread'}) => frozenset({'Bacon'}) [0.48, 0.04]
frozenset({'Toothpaste'}) => frozenset({'Bread'}) [0.44, 0.04]
frozenset({'Bread'}) => frozenset({'Toothpaste'}) [0.44, 0.04]
frozenset({'Banana'}) => frozenset({'Bread'}) [0.49, 0.06]
frozenset({'Bread'}) => frozenset({'Banana'}) [0.49, 0.06]
frozenset({'Apple'}) => frozenset({'Bread'}) [0.43, 0.00]
frozenset({'Bread'}) => frozenset({'Apple'}) [0.43, 0.00]
frozenset({'Hazelnut'}) => frozenset({'Bread'}) [0.45, 0.02]
frozenset({'Bread'}) => frozenset({'Hazelnut'}) [0.45, 0.02]
frozenset({'Cheese'}) => frozenset({'Bread'}) [0.51, 0.06]
frozenset({'Bread'}) => frozenset({'Cheese'}) [0.51, 0.06]
frozenset({'Meat'}) => frozenset({'Bread'}) [0.43, 0.03]
frozenset({'Bread'}) => frozenset({'Meat'}) [0.43, 0.03]
frozenset({'Carrot'}) => frozenset({'Bread'}) [0.47, 0.01]
frozenset({'Bread'}) => frozenset({'Carrot'}) [0.47, 0.01]
frozenset({'Cucumber'}) => frozenset({'Bread'}) [0.42, 0.04]
frozenset({'Bread'}) => frozenset({'Cucumber'}) [0.42, 0.04]
frozenset({'Onion'}) => frozenset({'Bread'}) [0.42, 0.05]
frozenset({'Bread'}) => frozenset({'Onion'}) [0.42, 0.05]
frozenset({'Milk'}) => frozenset({'Bread'}) [0.46, 0.06]
frozenset({'Bread'}) => frozenset({'Milk'}) [0.46, 0.06]
frozenset({'Butter'}) => frozenset({'Bread'}) [0.50, 0.06]
frozenset({'Bread'}) => frozenset({'Butter'}) [0.50, 0.06]
frozenset({'ShavingFoam'}) => frozenset({'Bread'}) [0.46, 0.00]
frozenset({'Bread'}) => frozenset({'ShavingFoam'}) [0.46, 0.00]
frozenset({'Salt'}) => frozenset({'Bread'}) [0.51, 0.01]
frozenset({'Bread'}) => frozenset({'Salt'}) [0.51, 0.01]
frozenset({'Flour'}) => frozenset({'Bread'}) [0.44, 0.03]
frozenset({'Bread'}) => frozenset({'Flour'}) [0.44, 0.03]
frozenset({'HeavyCream'}) => frozenset({'Bread'}) [0.46, 0.01]
frozenset({'Bread'}) => frozenset({'HeavyCream'}) [0.46, 0.01]
frozenset({'Egg'}) => frozenset({'Bread'}) [0.46, 0.01]
frozenset({'Bread'}) => frozenset({'Egg'}) [0.46, 0.01]
frozenset({'Olive'}) => frozenset({'Bread'}) [0.43, 0.04]
frozenset({'Bread'}) => frozenset({'Olive'}) [0.43, 0.04]
frozenset({'Shampoo'}) => frozenset({'Bread'}) [0.45, 0.07]
frozenset({'Bread'}) => frozenset({'Shampoo'}) [0.45, 0.07]
frozenset({'Sugar'}) => frozenset({'Bread'}) [0.45, 0.07]
frozenset({'Bread'}) => frozenset({'Sugar'}) [0.45, 0.07]
frozenset({'Bacon'}) => frozenset({'Honey'}) [0.48, 0.02]
frozenset({'Honey'}) => frozenset({'Bacon'}) [0.48, 0.02]
frozenset({'Toothpaste'}) => frozenset({'Honey'}) [0.45, 0.05]
frozenset({'Honey'}) => frozenset({'Toothpaste'}) [0.45, 0.05]
frozenset({'Banana'}) => frozenset({'Honey'}) [0.49, 0.05]
frozenset({'Honey'}) => frozenset({'Banana'}) [0.49, 0.05]
frozenset({'Apple'}) => frozenset({'Honey'}) [0.46, 0.02]
frozenset({'Honey'}) => frozenset({'Apple'}) [0.46, 0.02]
frozenset({'Hazelnut'}) => frozenset({'Honey'}) [0.46, 0.01]
frozenset({'Honey'}) => frozenset({'Hazelnut'}) [0.46, 0.01]
frozenset({'Cheese'}) => frozenset({'Honey'}) [0.51, 0.04]
frozenset({'Honey'}) => frozenset({'Cheese'}) [0.51, 0.04]
frozenset({'Meat'}) => frozenset({'Honey'}) [0.50, 0.05]
frozenset({'Honey'}) => frozenset({'Meat'}) [0.50, 0.05]
frozenset({'Carrot'}) => frozenset({'Honey'}) [0.49, 0.00]
frozenset({'Honey'}) => frozenset({'Carrot'}) [0.49, 0.00]
frozenset({'Cucumber'}) => frozenset({'Honey'}) [0.42, 0.05]
frozenset({'Honey'}) => frozenset({'Cucumber'}) [0.42, 0.05]
frozenset({'Onion'}) => frozenset({'Honey'}) [0.45, 0.06]
frozenset({'Honey'}) => frozenset({'Onion'}) [0.45, 0.06]
frozenset({'Milk'}) => frozenset({'Honey'}) [0.45, 0.07]
frozenset({'Honey'}) => frozenset({'Milk'}) [0.45, 0.07]
frozenset({'Butter'}) => frozenset({'Honey'}) [0.47, 0.07]
frozenset({'Honey'}) => frozenset({'Butter'}) [0.47, 0.07]
frozenset({'ShavingFoam'}) => frozenset({'Honey'}) [0.46, 0.02]
frozenset({'Honey'}) => frozenset({'ShavingFoam'}) [0.46, 0.02]
frozenset({'Salt'}) => frozenset({'Honey'}) [0.41, 0.03]
frozenset({'Honey'}) => frozenset({'Salt'}) [0.41, 0.03]
frozenset({'Flour'}) => frozenset({'Honey'}) [0.42, 0.05]
frozenset({'Honey'}) => frozenset({'Flour'}) [0.42, 0.05]
frozenset({'HeavyCream'}) => frozenset({'Honey'}) [0.49, 0.00]
frozenset({'Honey'}) => frozenset({'HeavyCream'}) [0.49, 0.00]
frozenset({'Egg'}) => frozenset({'Honey'}) [0.51, 0.02]
frozenset({'Honey'}) => frozenset({'Egg'}) [0.51, 0.02]
frozenset({'Olive'}) => frozenset({'Honey'}) [0.40, 0.05]
frozenset({'Honey'}) => frozenset({'Olive'}) [0.40, 0.05]
frozenset({'Shampoo'}) => frozenset({'Honey'}) [0.48, 0.08]
frozenset({'Honey'}) => frozenset({'Shampoo'}) [0.48, 0.08]
frozenset({'Sugar'}) => frozenset({'Honey'}) [0.44, 0.08]
frozenset({'Honey'}) => frozenset({'Sugar'}) [0.44, 0.08]
frozenset({'Toothpaste'}) => frozenset({'Bacon'}) [0.43, 0.07]
frozenset({'Bacon'}) => frozenset({'Toothpaste'}) [0.43, 0.07]
frozenset({'Banana'}) => frozenset({'Bacon'}) [0.55, 0.03]
frozenset({'Bacon'}) => frozenset({'Banana'}) [0.55, 0.03]
frozenset({'Apple'}) => frozenset({'Bacon'}) [0.45, 0.04]
frozenset({'Bacon'}) => frozenset({'Apple'}) [0.45, 0.04]
frozenset({'Hazelnut'}) => frozenset({'Bacon'}) [0.52, 0.02]
frozenset({'Bacon'}) => frozenset({'Hazelnut'}) [0.52, 0.02]
frozenset({'Cheese'}) => frozenset({'Bacon'}) [0.51, 0.02]
frozenset({'Bacon'}) => frozenset({'Cheese'}) [0.51, 0.02]
frozenset({'Meat'}) => frozenset({'Bacon'}) [0.53, 0.07]
frozenset({'Bacon'}) => frozenset({'Meat'}) [0.53, 0.07]
frozenset({'Carrot'}) => frozenset({'Bacon'}) [0.47, 0.03]
frozenset({'Bacon'}) => frozenset({'Carrot'}) [0.47, 0.03]
frozenset({'Cucumber'}) => frozenset({'Bacon'}) [0.45, 0.08]
frozenset({'Bacon'}) => frozenset({'Cucumber'}) [0.45, 0.08]
frozenset({'Onion'}) => frozenset({'Bacon'}) [0.46, 0.08]
frozenset({'Bacon'}) => frozenset({'Onion'}) [0.46, 0.08]
frozenset({'Milk'}) => frozenset({'Bacon'}) [0.47, 0.10]
frozenset({'Bacon'}) => frozenset({'Milk'}) [0.47, 0.10]
frozenset({'Bacon'}) => frozenset({'Butter'}) [0.52, 0.09]
frozenset({'Butter'}) => frozenset({'Bacon'}) [0.52, 0.09]
frozenset({'ShavingFoam'}) => frozenset({'Bacon'}) [0.52, 0.04]
frozenset({'Bacon'}) => frozenset({'ShavingFoam'}) [0.52, 0.04]
frozenset({'Salt'}) => frozenset({'Bacon'}) [0.41, 0.05]
frozenset({'Bacon'}) => frozenset({'Salt'}) [0.41, 0.05]
frozenset({'Flour'}) => frozenset({'Bacon'}) [0.41, 0.07]
frozenset({'Bacon'}) => frozenset({'Flour'}) [0.41, 0.07]
frozenset({'HeavyCream'}) => frozenset({'Bacon'}) [0.47, 0.02]
frozenset({'Bacon'}) => frozenset({'HeavyCream'}) [0.47, 0.02]
frozenset({'Egg'}) => frozenset({'Bacon'}) [0.49, 0.04]
frozenset({'Bacon'}) => frozenset({'Egg'}) [0.49, 0.04]
frozenset({'Olive'}) => frozenset({'Bacon'}) [0.44, 0.08]
frozenset({'Bacon'}) => frozenset({'Olive'}) [0.44, 0.08]
frozenset({'Bacon'}) => frozenset({'Shampoo'}) [0.42, 0.10]
frozenset({'Shampoo'}) => frozenset({'Bacon'}) [0.42, 0.10]
frozenset({'Sugar'}) => frozenset({'Bacon'}) [0.47, 0.11]
frozenset({'Bacon'}) => frozenset({'Sugar'}) [0.47, 0.11]
frozenset({'Banana'}) => frozenset({'Toothpaste'}) [0.49, 0.10]
frozenset({'Toothpaste'}) => frozenset({'Banana'}) [0.49, 0.10]
frozenset({'Toothpaste'}) => frozenset({'Apple'}) [0.46, 0.04]
frozenset({'Apple'}) => frozenset({'Toothpaste'}) [0.46, 0.04]
frozenset({'Hazelnut'}) => frozenset({'Toothpaste'}) [0.51, 0.06]
frozenset({'Toothpaste'}) => frozenset({'Hazelnut'}) [0.51, 0.06]
frozenset({'Cheese'}) => frozenset({'Toothpaste'}) [0.48, 0.10]
frozenset({'Toothpaste'}) => frozenset({'Cheese'}) [0.48, 0.10]
frozenset({'Toothpaste'}) => frozenset({'Meat'}) [0.44, 0.01]
frozenset({'Meat'}) => frozenset({'Toothpaste'}) [0.44, 0.01]
frozenset({'Toothpaste'}) => frozenset({'Carrot'}) [0.51, 0.05]
frozenset({'Carrot'}) => frozenset({'Toothpaste'}) [0.51, 0.05]
frozenset({'Toothpaste'}) => frozenset({'Cucumber'}) [0.45, 0.00]
frozenset({'Cucumber'}) => frozenset({'Toothpaste'}) [0.45, 0.00]
frozenset({'Toothpaste'}) => frozenset({'Onion'}) [0.51, 0.01]
frozenset({'Onion'}) => frozenset({'Toothpaste'}) [0.51, 0.01]
frozenset({'Toothpaste'}) => frozenset({'Milk'}) [0.47, 0.02]
frozenset({'Milk'}) => frozenset({'Toothpaste'}) [0.47, 0.02]
frozenset({'Toothpaste'}) => frozenset({'Butter'}) [0.48, 0.01]
frozenset({'Butter'}) => frozenset({'Toothpaste'}) [0.48, 0.01]
frozenset({'ShavingFoam'}) => frozenset({'Toothpaste'}) [0.48, 0.04]
frozenset({'Toothpaste'}) => frozenset({'ShavingFoam'}) [0.48, 0.04]
frozenset({'Toothpaste'}) => frozenset({'Salt'}) [0.50, 0.03]
frozenset({'Salt'}) => frozenset({'Toothpaste'}) [0.50, 0.03]
frozenset({'Flour'}) => frozenset({'Toothpaste'}) [0.48, 0.00]
frozenset({'Toothpaste'}) => frozenset({'Flour'}) [0.48, 0.00]
frozenset({'Toothpaste'}) => frozenset({'HeavyCream'}) [0.48, 0.05]
frozenset({'HeavyCream'}) => frozenset({'Toothpaste'}) [0.48, 0.05]
frozenset({'Egg'}) => frozenset({'Toothpaste'}) [0.46, 0.03]
frozenset({'Toothpaste'}) => frozenset({'Egg'}) [0.46, 0.03]
frozenset({'Toothpaste'}) => frozenset({'Olive'}) [0.45, 0.00]
frozenset({'Olive'}) => frozenset({'Toothpaste'}) [0.45, 0.00]
frozenset({'Toothpaste'}) => frozenset({'Shampoo'}) [0.39, 0.03]
frozenset({'Shampoo'}) => frozenset({'Toothpaste'}) [0.39, 0.03]
frozenset({'Toothpaste'}) => frozenset({'Sugar'}) [0.47, 0.03]
frozenset({'Sugar'}) => frozenset({'Toothpaste'}) [0.47, 0.03]
frozenset({'Banana'}) => frozenset({'Apple'}) [0.52, 0.07]
frozenset({'Apple'}) => frozenset({'Banana'}) [0.52, 0.07]
frozenset({'Banana'}) => frozenset({'Hazelnut'}) [0.51, 0.04]
frozenset({'Hazelnut'}) => frozenset({'Banana'}) [0.51, 0.04]
frozenset({'Banana'}) => frozenset({'Cheese'}) [0.50, 0.01]
frozenset({'Cheese'}) => frozenset({'Banana'}) [0.50, 0.01]
frozenset({'Banana'}) => frozenset({'Meat'}) [0.46, 0.09]
frozenset({'Meat'}) => frozenset({'Banana'}) [0.46, 0.09]
frozenset({'Banana'}) => frozenset({'Carrot'}) [0.51, 0.05]
frozenset({'Carrot'}) => frozenset({'Banana'}) [0.51, 0.05]
frozenset({'Banana'}) => frozenset({'Cucumber'}) [0.48, 0.11]
frozenset({'Cucumber'}) => frozenset({'Banana'}) [0.48, 0.11]
frozenset({'Banana'}) => frozenset({'Onion'}) [0.51, 0.11]
frozenset({'Onion'}) => frozenset({'Banana'}) [0.51, 0.11]
frozenset({'Banana'}) => frozenset({'Milk'}) [0.45, 0.12]
frozenset({'Milk'}) => frozenset({'Banana'}) [0.45, 0.12]
frozenset({'Banana'}) => frozenset({'Butter'}) [0.44, 0.11]
frozenset({'Butter'}) => frozenset({'Banana'}) [0.44, 0.11]
frozenset({'Banana'}) => frozenset({'ShavingFoam'}) [0.52, 0.07]
frozenset({'ShavingFoam'}) => frozenset({'Banana'}) [0.52, 0.07]
frozenset({'Banana'}) => frozenset({'Salt'}) [0.46, 0.08]
frozenset({'Salt'}) => frozenset({'Banana'}) [0.46, 0.08]
frozenset({'Flour'}) => frozenset({'Banana'}) [0.45, 0.10]
frozenset({'Banana'}) => frozenset({'Flour'}) [0.45, 0.10]
frozenset({'Banana'}) => frozenset({'HeavyCream'}) [0.45, 0.05]
frozenset({'HeavyCream'}) => frozenset({'Banana'}) [0.45, 0.05]
frozenset({'Banana'}) => frozenset({'Egg'}) [0.50, 0.07]
frozenset({'Egg'}) => frozenset({'Banana'}) [0.50, 0.07]
frozenset({'Banana'}) => frozenset({'Olive'}) [0.50, 0.11]
frozenset({'Olive'}) => frozenset({'Banana'}) [0.50, 0.11]
frozenset({'Banana'}) => frozenset({'Shampoo'}) [0.44, 0.13]
frozenset({'Shampoo'}) => frozenset({'Banana'}) [0.44, 0.13]
frozenset({'Banana'}) => frozenset({'Sugar'}) [0.44, 0.13]
frozenset({'Sugar'}) => frozenset({'Banana'}) [0.44, 0.13]
frozenset({'Hazelnut'}) => frozenset({'Apple'}) [0.41, 0.02]
frozenset({'Apple'}) => frozenset({'Hazelnut'}) [0.41, 0.02]
frozenset({'Cheese'}) => frozenset({'Apple'}) [0.43, 0.06]
frozenset({'Apple'}) => frozenset({'Cheese'}) [0.43, 0.06]
frozenset({'Meat'}) => frozenset({'Apple'}) [0.48, 0.03]
frozenset({'Apple'}) => frozenset({'Meat'}) [0.48, 0.03]
frozenset({'Apple'}) => frozenset({'Carrot'}) [0.46, 0.01]
frozenset({'Carrot'}) => frozenset({'Apple'}) [0.46, 0.01]
frozenset({'Cucumber'}) => frozenset({'Apple'}) [0.40, 0.04]
frozenset({'Apple'}) => frozenset({'Cucumber'}) [0.40, 0.04]
frozenset({'Onion'}) => frozenset({'Apple'}) [0.47, 0.04]
frozenset({'Apple'}) => frozenset({'Onion'}) [0.47, 0.04]
frozenset({'Milk'}) => frozenset({'Apple'}) [0.42, 0.06]
frozenset({'Apple'}) => frozenset({'Milk'}) [0.42, 0.06]
frozenset({'Apple'}) => frozenset({'Butter'}) [0.45, 0.05]
frozenset({'Butter'}) => frozenset({'Apple'}) [0.45, 0.05]
frozenset({'ShavingFoam'}) => frozenset({'Apple'}) [0.45, 0.00]
frozenset({'Apple'}) => frozenset({'ShavingFoam'}) [0.45, 0.00]
frozenset({'Salt'}) => frozenset({'Apple'}) [0.45, 0.01]
frozenset({'Apple'}) => frozenset({'Salt'}) [0.45, 0.01]
frozenset({'Flour'}) => frozenset({'Apple'}) [0.43, 0.03]
frozenset({'Apple'}) => frozenset({'Flour'}) [0.43, 0.03]
frozenset({'HeavyCream'}) => frozenset({'Apple'}) [0.48, 0.02]
frozenset({'Apple'}) => frozenset({'HeavyCream'}) [0.48, 0.02]
frozenset({'Egg'}) => frozenset({'Apple'}) [0.49, 0.00]
frozenset({'Apple'}) => frozenset({'Egg'}) [0.49, 0.00]
frozenset({'Olive'}) => frozenset({'Apple'}) [0.48, 0.04]
frozenset({'Apple'}) => frozenset({'Olive'}) [0.48, 0.04]
frozenset({'Apple'}) => frozenset({'Shampoo'}) [0.45, 0.06]
frozenset({'Shampoo'}) => frozenset({'Apple'}) [0.45, 0.06]
frozenset({'Apple'}) => frozenset({'Sugar'}) [0.42, 0.06]
frozenset({'Sugar'}) => frozenset({'Apple'}) [0.42, 0.06]
frozenset({'Cheese'}) => frozenset({'Hazelnut'}) [0.48, 0.04]
frozenset({'Hazelnut'}) => frozenset({'Cheese'}) [0.48, 0.04]
frozenset({'Hazelnut'}) => frozenset({'Meat'}) [0.48, 0.05]
frozenset({'Meat'}) => frozenset({'Hazelnut'}) [0.48, 0.05]
frozenset({'Hazelnut'}) => frozenset({'Carrot'}) [0.44, 0.01]
frozenset({'Carrot'}) => frozenset({'Hazelnut'}) [0.44, 0.01]
frozenset({'Hazelnut'}) => frozenset({'Cucumber'}) [0.47, 0.06]
frozenset({'Cucumber'}) => frozenset({'Hazelnut'}) [0.47, 0.06]
frozenset({'Hazelnut'}) => frozenset({'Onion'}) [0.45, 0.07]
frozenset({'Onion'}) => frozenset({'Hazelnut'}) [0.45, 0.07]
frozenset({'Hazelnut'}) => frozenset({'Milk'}) [0.46, 0.08]
frozenset({'Milk'}) => frozenset({'Hazelnut'}) [0.46, 0.08]
frozenset({'Hazelnut'}) => frozenset({'Butter'}) [0.50, 0.08]
frozenset({'Butter'}) => frozenset({'Hazelnut'}) [0.50, 0.08]
frozenset({'ShavingFoam'}) => frozenset({'Hazelnut'}) [0.46, 0.02]
frozenset({'Hazelnut'}) => frozenset({'ShavingFoam'}) [0.46, 0.02]
frozenset({'Hazelnut'}) => frozenset({'Salt'}) [0.45, 0.03]
frozenset({'Salt'}) => frozenset({'Hazelnut'}) [0.45, 0.03]
frozenset({'Flour'}) => frozenset({'Hazelnut'}) [0.50, 0.06]
frozenset({'Hazelnut'}) => frozenset({'Flour'}) [0.50, 0.06]
frozenset({'Hazelnut'}) => frozenset({'HeavyCream'}) [0.50, 0.01]
frozenset({'HeavyCream'}) => frozenset({'Hazelnut'}) [0.50, 0.01]
frozenset({'Hazelnut'}) => frozenset({'Egg'}) [0.48, 0.03]
frozenset({'Egg'}) => frozenset({'Hazelnut'}) [0.48, 0.03]
frozenset({'Hazelnut'}) => frozenset({'Olive'}) [0.45, 0.06]
frozenset({'Olive'}) => frozenset({'Hazelnut'}) [0.45, 0.06]
frozenset({'Hazelnut'}) => frozenset({'Shampoo'}) [0.45, 0.09]
frozenset({'Shampoo'}) => frozenset({'Hazelnut'}) [0.45, 0.09]
frozenset({'Hazelnut'}) => frozenset({'Sugar'}) [0.46, 0.09]
frozenset({'Sugar'}) => frozenset({'Hazelnut'}) [0.46, 0.09]
frozenset({'Cheese'}) => frozenset({'Meat'}) [0.49, 0.09]
frozenset({'Meat'}) => frozenset({'Cheese'}) [0.49, 0.09]
frozenset({'Cheese'}) => frozenset({'Carrot'}) [0.51, 0.05]
frozenset({'Carrot'}) => frozenset({'Cheese'}) [0.51, 0.05]
frozenset({'Cheese'}) => frozenset({'Cucumber'}) [0.47, 0.10]
frozenset({'Cucumber'}) => frozenset({'Cheese'}) [0.47, 0.10]
frozenset({'Cheese'}) => frozenset({'Onion'}) [0.47, 0.10]
frozenset({'Onion'}) => frozenset({'Cheese'}) [0.47, 0.10]
frozenset({'Cheese'}) => frozenset({'Milk'}) [0.44, 0.12]
frozenset({'Milk'}) => frozenset({'Cheese'}) [0.44, 0.12]
frozenset({'Cheese'}) => frozenset({'Butter'}) [0.53, 0.11]
frozenset({'Butter'}) => frozenset({'Cheese'}) [0.53, 0.11]
frozenset({'ShavingFoam'}) => frozenset({'Cheese'}) [0.50, 0.06]
frozenset({'Cheese'}) => frozenset({'ShavingFoam'}) [0.50, 0.06]
frozenset({'Cheese'}) => frozenset({'Salt'}) [0.48, 0.07]
frozenset({'Salt'}) => frozenset({'Cheese'}) [0.48, 0.07]
frozenset({'Flour'}) => frozenset({'Cheese'}) [0.46, 0.09]
frozenset({'Cheese'}) => frozenset({'Flour'}) [0.46, 0.09]
frozenset({'Cheese'}) => frozenset({'HeavyCream'}) [0.47, 0.04]
frozenset({'HeavyCream'}) => frozenset({'Cheese'}) [0.47, 0.04]
frozenset({'Cheese'}) => frozenset({'Egg'}) [0.53, 0.07]
frozenset({'Egg'}) => frozenset({'Cheese'}) [0.53, 0.07]
frozenset({'Cheese'}) => frozenset({'Olive'}) [0.41, 0.10]
frozenset({'Olive'}) => frozenset({'Cheese'}) [0.41, 0.10]
frozenset({'Cheese'}) => frozenset({'Shampoo'}) [0.47, 0.12]
frozenset({'Shampoo'}) => frozenset({'Cheese'}) [0.47, 0.12]
frozenset({'Cheese'}) => frozenset({'Sugar'}) [0.47, 0.12]
frozenset({'Sugar'}) => frozenset({'Cheese'}) [0.47, 0.12]
frozenset({'Meat'}) => frozenset({'Carrot'}) [0.42, 0.04]
frozenset({'Carrot'}) => frozenset({'Meat'}) [0.42, 0.04]
frozenset({'Meat'}) => frozenset({'Cucumber'}) [0.43, 0.01]
frozenset({'Cucumber'}) => frozenset({'Meat'}) [0.43, 0.01]
frozenset({'Meat'}) => frozenset({'Onion'}) [0.47, 0.01]
frozenset({'Onion'}) => frozenset({'Meat'}) [0.47, 0.01]
frozenset({'Milk'}) => frozenset({'Meat'}) [0.40, 0.03]
frozenset({'Meat'}) => frozenset({'Milk'}) [0.40, 0.03]
frozenset({'Meat'}) => frozenset({'Butter'}) [0.43, 0.02]
frozenset({'Butter'}) => frozenset({'Meat'}) [0.43, 0.02]
frozenset({'ShavingFoam'}) => frozenset({'Meat'}) [0.46, 0.03]
frozenset({'Meat'}) => frozenset({'ShavingFoam'}) [0.46, 0.03]
frozenset({'Meat'}) => frozenset({'Salt'}) [0.44, 0.02]
frozenset({'Salt'}) => frozenset({'Meat'}) [0.44, 0.02]
frozenset({'Flour'}) => frozenset({'Meat'}) [0.38, 0.00]
frozenset({'Meat'}) => frozenset({'Flour'}) [0.38, 0.00]
frozenset({'Meat'}) => frozenset({'HeavyCream'}) [0.48, 0.05]
frozenset({'HeavyCream'}) => frozenset({'Meat'}) [0.48, 0.05]
frozenset({'Egg'}) => frozenset({'Meat'}) [0.47, 0.02]
frozenset({'Meat'}) => frozenset({'Egg'}) [0.47, 0.02]
frozenset({'Meat'}) => frozenset({'Olive'}) [0.44, 0.01]
frozenset({'Olive'}) => frozenset({'Meat'}) [0.44, 0.01]
frozenset({'Meat'}) => frozenset({'Shampoo'}) [0.47, 0.04]
frozenset({'Shampoo'}) => frozenset({'Meat'}) [0.47, 0.04]
frozenset({'Meat'}) => frozenset({'Sugar'}) [0.50, 0.04]
frozenset({'Sugar'}) => frozenset({'Meat'}) [0.50, 0.04]
frozenset({'Cucumber'}) => frozenset({'Carrot'}) [0.44, 0.05]
frozenset({'Carrot'}) => frozenset({'Cucumber'}) [0.44, 0.05]
frozenset({'Onion'}) => frozenset({'Carrot'}) [0.46, 0.06]
frozenset({'Carrot'}) => frozenset({'Onion'}) [0.46, 0.06]
frozenset({'Milk'}) => frozenset({'Carrot'}) [0.44, 0.07]
frozenset({'Carrot'}) => frozenset({'Milk'}) [0.44, 0.07]
frozenset({'Carrot'}) => frozenset({'Butter'}) [0.41, 0.06]
frozenset({'Butter'}) => frozenset({'Carrot'}) [0.41, 0.06]
frozenset({'ShavingFoam'}) => frozenset({'Carrot'}) [0.45, 0.01]
frozenset({'Carrot'}) => frozenset({'ShavingFoam'}) [0.45, 0.01]
frozenset({'Salt'}) => frozenset({'Carrot'}) [0.46, 0.02]
frozenset({'Carrot'}) => frozenset({'Salt'}) [0.46, 0.02]
frozenset({'Flour'}) => frozenset({'Carrot'}) [0.44, 0.04]
frozenset({'Carrot'}) => frozenset({'Flour'}) [0.44, 0.04]
frozenset({'HeavyCream'}) => frozenset({'Carrot'}) [0.48, 0.00]
frozenset({'Carrot'}) => frozenset({'HeavyCream'}) [0.48, 0.00]
frozenset({'Egg'}) => frozenset({'Carrot'}) [0.50, 0.02]
frozenset({'Carrot'}) => frozenset({'Egg'}) [0.50, 0.02]
frozenset({'Olive'}) => frozenset({'Carrot'}) [0.47, 0.05]
frozenset({'Carrot'}) => frozenset({'Olive'}) [0.47, 0.05]
frozenset({'Carrot'}) => frozenset({'Shampoo'}) [0.43, 0.08]
frozenset({'Shampoo'}) => frozenset({'Carrot'}) [0.43, 0.08]
frozenset({'Sugar'}) => frozenset({'Carrot'}) [0.40, 0.08]
frozenset({'Carrot'}) => frozenset({'Sugar'}) [0.40, 0.08]
frozenset({'Onion'}) => frozenset({'Cucumber'}) [0.47, 0.00]
frozenset({'Cucumber'}) => frozenset({'Onion'}) [0.47, 0.00]

In [79]:
for _, row in association_rules_fpgrowth.iterrows():
    print(f"{row['antecedents']} => {row['consequents']} "
          f"[{row['kulczynski']:.2f}, {row['imbalance ratio']:.2f}]")

frozenset({'Banana'}) => frozenset({'Bacon'}) [0.55, 0.03]
frozenset({'Bacon'}) => frozenset({'Banana'}) [0.55, 0.03]
frozenset({'Cheese'}) => frozenset({'Bacon'}) [0.51, 0.02]
frozenset({'Bacon'}) => frozenset({'Cheese'}) [0.51, 0.02]
frozenset({'Banana', 'Cheese'}) => frozenset({'Bacon'}) [0.47, 0.40]
frozenset({'Banana', 'Bacon'}) => frozenset({'Cheese'}) [0.45, 0.37]
frozenset({'Cheese', 'Bacon'}) => frozenset({'Banana'}) [0.47, 0.42]
frozenset({'Banana'}) => frozenset({'Cheese', 'Bacon'}) [0.47, 0.42]
frozenset({'Cheese'}) => frozenset({'Banana', 'Bacon'}) [0.45, 0.37]
frozenset({'Bacon'}) => frozenset({'Banana', 'Cheese'}) [0.47, 0.40]
frozenset({'Hazelnut'}) => frozenset({'Bacon'}) [0.52, 0.02]
frozenset({'Bacon'}) => frozenset({'Hazelnut'}) [0.52, 0.02]
frozenset({'Banana'}) => frozenset({'Hazelnut'}) [0.51, 0.04]
frozenset({'Hazelnut'}) => frozenset({'Banana'}) [0.51, 0.04]
frozenset({'Cheese'}) => frozenset({'Hazelnut'}) [0.48, 0.04]
frozenset({'Hazelnut'}) => frozenset({'Cheese'}) [0.48, 0.04]
frozenset({'Banana', 'Hazelnut'}) => frozenset({'Bacon'}) [0.43, 0.40]
frozenset({'Banana', 'Bacon'}) => frozenset({'Hazelnut'}) [0.41, 0.33]
frozenset({'Hazelnut', 'Bacon'}) => frozenset({'Banana'}) [0.43, 0.42]
frozenset({'Banana'}) => frozenset({'Hazelnut', 'Bacon'}) [0.43, 0.42]
frozenset({'Hazelnut'}) => frozenset({'Banana', 'Bacon'}) [0.41, 0.33]
frozenset({'Bacon'}) => frozenset({'Banana', 'Hazelnut'}) [0.43, 0.40]
frozenset({'Cheese', 'Hazelnut'}) => frozenset({'Bacon'}) [0.45, 0.44]
frozenset({'Cheese', 'Bacon'}) => frozenset({'Hazelnut'}) [0.43, 0.38]
frozenset({'Hazelnut', 'Bacon'}) => frozenset({'Cheese'}) [0.42, 0.41]
frozenset({'Cheese'}) => frozenset({'Hazelnut', 'Bacon'}) [0.42, 0.41]
frozenset({'Hazelnut'}) => frozenset({'Cheese', 'Bacon'}) [0.43, 0.38]
frozenset({'Bacon'}) => frozenset({'Cheese', 'Hazelnut'}) [0.45, 0.44]
frozenset({'Banana', 'Cheese'}) => frozenset({'Hazelnut'}) [0.39, 0.37]
frozenset({'Banana', 'Hazelnut'}) => frozenset({'Cheese'}) [0.39, 0.40]
frozenset({'Cheese', 'Hazelnut'}) => frozenset({'Banana'}) [0.40, 0.45]
frozenset({'Banana'}) => frozenset({'Cheese', 'Hazelnut'}) [0.40, 0.45]
frozenset({'Cheese'}) => frozenset({'Banana', 'Hazelnut'}) [0.39, 0.40]
frozenset({'Hazelnut'}) => frozenset({'Banana', 'Cheese'}) [0.39, 0.37]
frozenset({'Hazelnut'}) => frozenset({'HeavyCream'}) [0.50, 0.01]
frozenset({'HeavyCream'}) => frozenset({'Hazelnut'}) [0.50, 0.01]
frozenset({'HeavyCream'}) => frozenset({'Bacon'}) [0.47, 0.02]
frozenset({'Bacon'}) => frozenset({'HeavyCream'}) [0.47, 0.02]
frozenset({'Banana'}) => frozenset({'HeavyCream'}) [0.45, 0.05]
frozenset({'HeavyCream'}) => frozenset({'Banana'}) [0.45, 0.05]
frozenset({'Cheese'}) => frozenset({'HeavyCream'}) [0.47, 0.04]
frozenset({'HeavyCream'}) => frozenset({'Cheese'}) [0.47, 0.04]
frozenset({'Hazelnut', 'HeavyCream'}) => frozenset({'Bacon'}) [0.41, 0.42]
frozenset({'Hazelnut', 'Bacon'}) => frozenset({'HeavyCream'}) [0.40, 0.37]
frozenset({'HeavyCream', 'Bacon'}) => frozenset({'Hazelnut'}) [0.43, 0.44]
frozenset({'Hazelnut'}) => frozenset({'HeavyCream', 'Bacon'}) [0.43, 0.44]
frozenset({'HeavyCream'}) => frozenset({'Hazelnut', 'Bacon'}) [0.40, 0.37]
frozenset({'Bacon'}) => frozenset({'Hazelnut', 'HeavyCream'}) [0.41, 0.42]
frozenset({'Cheese', 'HeavyCream'}) => frozenset({'Bacon'}) [0.40, 0.44]
frozenset({'Cheese', 'Bacon'}) => frozenset({'HeavyCream'}) [0.38, 0.36]
frozenset({'HeavyCream', 'Bacon'}) => frozenset({'Cheese'}) [0.40, 0.46]
frozenset({'Cheese'}) => frozenset({'HeavyCream', 'Bacon'}) [0.40, 0.46]
frozenset({'HeavyCream'}) => frozenset({'Cheese', 'Bacon'}) [0.38, 0.36]
frozenset({'Bacon'}) => frozenset({'Cheese', 'HeavyCream'}) [0.40, 0.44]
frozenset({'Banana', 'HeavyCream'}) => frozenset({'Bacon'}) [0.45, 0.46]
frozenset({'Banana', 'Bacon'}) => frozenset({'HeavyCream'}) [0.40, 0.33]
frozenset({'HeavyCream', 'Bacon'}) => frozenset({'Banana'}) [0.44, 0.47]
frozenset({'Banana'}) => frozenset({'HeavyCream', 'Bacon'}) [0.44, 0.47]
frozenset({'HeavyCream'}) => frozenset({'Banana', 'Bacon'}) [0.40, 0.33]
frozenset({'Bacon'}) => frozenset({'Banana', 'HeavyCream'}) [0.45, 0.46]
frozenset({'Banana', 'Hazelnut'}) => frozenset({'HeavyCream'}) [0.39, 0.37]
frozenset({'Banana', 'HeavyCream'}) => frozenset({'Hazelnut'}) [0.43, 0.45]
frozenset({'Hazelnut', 'HeavyCream'}) => frozenset({'Banana'}) [0.40, 0.44]
frozenset({'Banana'}) => frozenset({'Hazelnut', 'HeavyCream'}) [0.40, 0.44]
frozenset({'Hazelnut'}) => frozenset({'Banana', 'HeavyCream'}) [0.43, 0.45]
frozenset({'HeavyCream'}) => frozenset({'Banana', 'Hazelnut'}) [0.39, 0.37]
frozenset({'Banana', 'Cheese'}) => frozenset({'HeavyCream'}) [0.36, 0.36]
frozenset({'Banana', 'HeavyCream'}) => frozenset({'Cheese'}) [0.38, 0.46]
frozenset({'Cheese', 'HeavyCream'}) => frozenset({'Banana'}) [0.37, 0.45]
frozenset({'Banana'}) => frozenset({'Cheese', 'HeavyCream'}) [0.37, 0.45]
frozenset({'Cheese'}) => frozenset({'Banana', 'HeavyCream'}) [0.38, 0.46]
frozenset({'HeavyCream'}) => frozenset({'Banana', 'Cheese'}) [0.36, 0.36]
frozenset({'Cheese', 'Hazelnut'}) => frozenset({'HeavyCream'}) [0.41, 0.41]
frozenset({'Cheese', 'HeavyCream'}) => frozenset({'Hazelnut'}) [0.41, 0.43]
frozenset({'Hazelnut', 'HeavyCream'}) => frozenset({'Cheese'}) [0.39, 0.43]
frozenset({'Cheese'}) => frozenset({'Hazelnut', 'HeavyCream'}) [0.39, 0.43]
frozenset({'Hazelnut'}) => frozenset({'Cheese', 'HeavyCream'}) [0.41, 0.43]
frozenset({'HeavyCream'}) => frozenset({'Cheese', 'Hazelnut'}) [0.41, 0.41]
frozenset({'Banana'}) => frozenset({'Carrot'}) [0.51, 0.05]
frozenset({'Carrot'}) => frozenset({'Banana'}) [0.51, 0.05]
frozenset({'HeavyCream'}) => frozenset({'Carrot'}) [0.48, 0.00]
frozenset({'Carrot'}) => frozenset({'HeavyCream'}) [0.48, 0.00]
frozenset({'Carrot'}) => frozenset({'Bacon'}) [0.47, 0.03]
frozenset({'Bacon'}) => frozenset({'Carrot'}) [0.47, 0.03]
frozenset({'Hazelnut'}) => frozenset({'Carrot'}) [0.44, 0.01]
frozenset({'Carrot'}) => frozenset({'Hazelnut'}) [0.44, 0.01]
frozenset({'Cheese'}) => frozenset({'Carrot'}) [0.51, 0.05]
frozenset({'Carrot'}) => frozenset({'Cheese'}) [0.51, 0.05]
frozenset({'Carrot'}) => frozenset({'Honey'}) [0.49, 0.00]
frozenset({'Honey'}) => frozenset({'Carrot'}) [0.49, 0.00]
frozenset({'Banana', 'HeavyCream'}) => frozenset({'Carrot'}) [0.42, 0.44]
frozenset({'Banana', 'Carrot'}) => frozenset({'HeavyCream'}) [0.39, 0.37]
frozenset({'HeavyCream', 'Carrot'}) => frozenset({'Banana'}) [0.41, 0.47]
frozenset({'Banana'}) => frozenset({'HeavyCream', 'Carrot'}) [0.41, 0.47]
frozenset({'HeavyCream'}) => frozenset({'Banana', 'Carrot'}) [0.39, 0.37]
frozenset({'Carrot'}) => frozenset({'Banana', 'HeavyCream'}) [0.42, 0.44]
frozenset({'HeavyCream', 'Carrot'}) => frozenset({'Honey'}) [0.41, 0.43]
frozenset({'HeavyCream', 'Honey'}) => frozenset({'Carrot'}) [0.40, 0.41]
frozenset({'Carrot', 'Honey'}) => frozenset({'HeavyCream'}) [0.40, 0.41]
frozenset({'HeavyCream'}) => frozenset({'Carrot', 'Honey'}) [0.40, 0.41]
frozenset({'Carrot'}) => frozenset({'HeavyCream', 'Honey'}) [0.40, 0.41]
frozenset({'Honey'}) => frozenset({'HeavyCream', 'Carrot'}) [0.41, 0.43]
frozenset({'Cheese', 'HeavyCream'}) => frozenset({'Carrot'}) [0.41, 0.42]
frozenset({'Cheese', 'Carrot'}) => frozenset({'HeavyCream'}) [0.38, 0.38]
frozenset({'HeavyCream', 'Carrot'}) => frozenset({'Cheese'}) [0.40, 0.46]
frozenset({'Cheese'}) => frozenset({'HeavyCream', 'Carrot'}) [0.40, 0.46]
frozenset({'HeavyCream'}) => frozenset({'Cheese', 'Carrot'}) [0.38, 0.38]
frozenset({'Carrot'}) => frozenset({'Cheese', 'HeavyCream'}) [0.41, 0.42]
frozenset({'Banana', 'Carrot'}) => frozenset({'Bacon'}) [0.41, 0.40]
frozenset({'Banana', 'Bacon'}) => frozenset({'Carrot'}) [0.40, 0.32]
frozenset({'Carrot', 'Bacon'}) => frozenset({'Banana'}) [0.44, 0.48]
frozenset({'Banana'}) => frozenset({'Carrot', 'Bacon'}) [0.44, 0.48]
frozenset({'Carrot'}) => frozenset({'Banana', 'Bacon'}) [0.40, 0.32]
frozenset({'Bacon'}) => frozenset({'Banana', 'Carrot'}) [0.41, 0.40]
frozenset({'HeavyCream', 'Carrot'}) => frozenset({'Bacon'}) [0.39, 0.44]
frozenset({'HeavyCream', 'Bacon'}) => frozenset({'Carrot'}) [0.39, 0.42]
frozenset({'Carrot', 'Bacon'}) => frozenset({'HeavyCream'}) [0.39, 0.43]
frozenset({'HeavyCream'}) => frozenset({'Carrot', 'Bacon'}) [0.39, 0.43]
frozenset({'Carrot'}) => frozenset({'HeavyCream', 'Bacon'}) [0.39, 0.42]
frozenset({'Bacon'}) => frozenset({'HeavyCream', 'Carrot'}) [0.39, 0.44]
frozenset({'Cheese', 'Carrot'}) => frozenset({'Bacon'}) [0.42, 0.41]
frozenset({'Cheese', 'Bacon'}) => frozenset({'Carrot'}) [0.42, 0.37]
frozenset({'Carrot', 'Bacon'}) => frozenset({'Cheese'}) [0.45, 0.47]
frozenset({'Cheese'}) => frozenset({'Carrot', 'Bacon'}) [0.45, 0.47]
frozenset({'Carrot'}) => frozenset({'Cheese', 'Bacon'}) [0.42, 0.37]
frozenset({'Bacon'}) => frozenset({'Cheese', 'Carrot'}) [0.42, 0.41]
frozenset({'Carrot', 'Bacon'}) => frozenset({'Honey'}) [0.43, 0.44]
frozenset({'Carrot', 'Honey'}) => frozenset({'Bacon'}) [0.41, 0.43]
frozenset({'Bacon', 'Honey'}) => frozenset({'Carrot'}) [0.42, 0.42]
frozenset({'Carrot'}) => frozenset({'Bacon', 'Honey'}) [0.42, 0.42]
frozenset({'Bacon'}) => frozenset({'Carrot', 'Honey'}) [0.41, 0.43]
frozenset({'Honey'}) => frozenset({'Carrot', 'Bacon'}) [0.43, 0.44]
frozenset({'Hazelnut', 'Carrot'}) => frozenset({'Bacon'}) [0.41, 0.49]
frozenset({'Hazelnut', 'Bacon'}) => frozenset({'Carrot'}) [0.37, 0.36]
frozenset({'Carrot', 'Bacon'}) => frozenset({'Hazelnut'}) [0.39, 0.43]
frozenset({'Hazelnut'}) => frozenset({'Carrot', 'Bacon'}) [0.39, 0.43]
frozenset({'Carrot'}) => frozenset({'Hazelnut', 'Bacon'}) [0.37, 0.36]
frozenset({'Bacon'}) => frozenset({'Hazelnut', 'Carrot'}) [0.41, 0.49]
frozenset({'Hazelnut', 'HeavyCream'}) => frozenset({'Carrot'}) [0.37, 0.39]
frozenset({'Hazelnut', 'Carrot'}) => frozenset({'HeavyCream'}) [0.41, 0.47]
frozenset({'HeavyCream', 'Carrot'}) => frozenset({'Hazelnut'}) [0.38, 0.43]
frozenset({'Hazelnut'}) => frozenset({'HeavyCream', 'Carrot'}) [0.38, 0.43]
frozenset({'HeavyCream'}) => frozenset({'Hazelnut', 'Carrot'}) [0.41, 0.47]
frozenset({'Carrot'}) => frozenset({'Hazelnut', 'HeavyCream'}) [0.37, 0.39]
frozenset({'Banana', 'Hazelnut'}) => frozenset({'Carrot'}) [0.36, 0.36]
frozenset({'Banana', 'Carrot'}) => frozenset({'Hazelnut'}) [0.36, 0.37]
frozenset({'Hazelnut', 'Carrot'}) => frozenset({'Banana'}) [0.40, 0.50]
frozenset({'Banana'}) => frozenset({'Hazelnut', 'Carrot'}) [0.40, 0.50]
frozenset({'Hazelnut'}) => frozenset({'Banana', 'Carrot'}) [0.36, 0.37]
frozenset({'Carrot'}) => frozenset({'Banana', 'Hazelnut'}) [0.36, 0.36]
frozenset({'Cheese', 'Hazelnut'}) => frozenset({'Carrot'}) [0.38, 0.40]
frozenset({'Cheese', 'Carrot'}) => frozenset({'Hazelnut'}) [0.36, 0.38]
frozenset({'Hazelnut', 'Carrot'}) => frozenset({'Cheese'}) [0.40, 0.50]
frozenset({'Cheese'}) => frozenset({'Hazelnut', 'Carrot'}) [0.40, 0.50]
frozenset({'Hazelnut'}) => frozenset({'Cheese', 'Carrot'}) [0.36, 0.38]
frozenset({'Carrot'}) => frozenset({'Cheese', 'Hazelnut'}) [0.38, 0.40]
frozenset({'Banana', 'Cheese'}) => frozenset({'Carrot'}) [0.44, 0.37]
frozenset({'Banana', 'Carrot'}) => frozenset({'Cheese'}) [0.43, 0.42]
frozenset({'Cheese', 'Carrot'}) => frozenset({'Banana'}) [0.43, 0.43]
frozenset({'Banana'}) => frozenset({'Cheese', 'Carrot'}) [0.43, 0.43]
frozenset({'Cheese'}) => frozenset({'Banana', 'Carrot'}) [0.43, 0.42]
frozenset({'Carrot'}) => frozenset({'Banana', 'Cheese'}) [0.44, 0.37]
frozenset({'Cheese', 'Carrot'}) => frozenset({'Honey'}) [0.44, 0.39]
frozenset({'Cheese', 'Honey'}) => frozenset({'Carrot'}) [0.44, 0.39]
frozenset({'Carrot', 'Honey'}) => frozenset({'Cheese'}) [0.45, 0.46]
frozenset({'Cheese'}) => frozenset({'Carrot', 'Honey'}) [0.45, 0.46]
frozenset({'Carrot'}) => frozenset({'Cheese', 'Honey'}) [0.44, 0.39]
frozenset({'Honey'}) => frozenset({'Cheese', 'Carrot'}) [0.44, 0.39]
frozenset({'Banana', 'Carrot'}) => frozenset({'Honey'}) [0.39, 0.37]
frozenset({'Banana', 'Honey'}) => frozenset({'Carrot'}) [0.40, 0.39]
frozenset({'Carrot', 'Honey'}) => frozenset({'Banana'}) [0.40, 0.45]
frozenset({'Banana'}) => frozenset({'Carrot', 'Honey'}) [0.40, 0.45]
frozenset({'Carrot'}) => frozenset({'Banana', 'Honey'}) [0.40, 0.39]
frozenset({'Honey'}) => frozenset({'Banana', 'Carrot'}) [0.39, 0.37]
frozenset({'Banana'}) => frozenset({'Bread'}) [0.49, 0.06]
frozenset({'Bread'}) => frozenset({'Banana'}) [0.49, 0.06]
frozenset({'Bacon'}) => frozenset({'Bread'}) [0.48, 0.04]
frozenset({'Bread'}) => frozenset({'Bacon'}) [0.48, 0.04]
frozenset({'Carrot'}) => frozenset({'Bread'}) [0.47, 0.01]
frozenset({'Bread'}) => frozenset({'Carrot'}) [0.47, 0.01]
frozenset({'HeavyCream'}) => frozenset({'Bread'}) [0.46, 0.01]
frozenset({'Bread'}) => frozenset({'HeavyCream'}) [0.46, 0.01]
frozenset({'Hazelnut'}) => frozenset({'Bread'}) [0.45, 0.02]
frozenset({'Bread'}) => frozenset({'Hazelnut'}) [0.45, 0.02]
frozenset({'Honey'}) => frozenset({'Bread'}) [0.49, 0.01]
frozenset({'Bread'}) => frozenset({'Honey'}) [0.49, 0.01]
frozenset({'Cheese'}) => frozenset({'Bread'}) [0.51, 0.06]
frozenset({'Bread'}) => frozenset({'Cheese'}) [0.51, 0.06]
frozenset({'Banana', 'Cheese'}) => frozenset({'Bread'}) [0.39, 0.35]
frozenset({'Banana', 'Bread'}) => frozenset({'Cheese'}) [0.39, 0.43]
frozenset({'Cheese', 'Bread'}) => frozenset({'Banana'}) [0.39, 0.42]
frozenset({'Banana'}) => frozenset({'Cheese', 'Bread'}) [0.39, 0.42]
frozenset({'Cheese'}) => frozenset({'Banana', 'Bread'}) [0.39, 0.43]
frozenset({'Bread'}) => frozenset({'Banana', 'Cheese'}) [0.39, 0.35]
frozenset({'Banana', 'Bacon'}) => frozenset({'Bread'}) [0.42, 0.32]
frozenset({'Banana', 'Bread'}) => frozenset({'Bacon'}) [0.45, 0.43]
frozenset({'Bacon', 'Bread'}) => frozenset({'Banana'}) [0.46, 0.47]
frozenset({'Banana'}) => frozenset({'Bacon', 'Bread'}) [0.46, 0.47]
frozenset({'Bacon'}) => frozenset({'Banana', 'Bread'}) [0.45, 0.43]
frozenset({'Bread'}) => frozenset({'Banana', 'Bacon'}) [0.42, 0.32]
frozenset({'Cheese', 'Bacon'}) => frozenset({'Bread'}) [0.42, 0.36]
frozenset({'Cheese', 'Bread'}) => frozenset({'Bacon'}) [0.42, 0.41]
frozenset({'Bacon', 'Bread'}) => frozenset({'Cheese'}) [0.43, 0.46]
frozenset({'Cheese'}) => frozenset({'Bacon', 'Bread'}) [0.43, 0.46]
frozenset({'Bacon'}) => frozenset({'Cheese', 'Bread'}) [0.42, 0.41]
frozenset({'Bread'}) => frozenset({'Cheese', 'Bacon'}) [0.42, 0.36]
frozenset({'Banana', 'Carrot'}) => frozenset({'Bread'}) [0.38, 0.36]
frozenset({'Banana', 'Bread'}) => frozenset({'Carrot'}) [0.39, 0.39]
frozenset({'Carrot', 'Bread'}) => frozenset({'Banana'}) [0.40, 0.48]
frozenset({'Banana'}) => frozenset({'Carrot', 'Bread'}) [0.40, 0.48]
frozenset({'Carrot'}) => frozenset({'Banana', 'Bread'}) [0.39, 0.39]
frozenset({'Bread'}) => frozenset({'Banana', 'Carrot'}) [0.38, 0.36]
frozenset({'Carrot', 'Honey'}) => frozenset({'Bread'}) [0.41, 0.41]
frozenset({'Bread', 'Honey'}) => frozenset({'Carrot'}) [0.41, 0.42]
frozenset({'Carrot', 'Bread'}) => frozenset({'Honey'}) [0.42, 0.45]
frozenset({'Honey'}) => frozenset({'Carrot', 'Bread'}) [0.42, 0.45]
frozenset({'Carrot'}) => frozenset({'Bread', 'Honey'}) [0.41, 0.42]
frozenset({'Bread'}) => frozenset({'Carrot', 'Honey'}) [0.41, 0.41]
frozenset({'Cheese', 'Carrot'}) => frozenset({'Bread'}) [0.39, 0.37]
frozenset({'Cheese', 'Bread'}) => frozenset({'Carrot'}) [0.40, 0.38]
frozenset({'Carrot', 'Bread'}) => frozenset({'Cheese'}) [0.42, 0.48]
frozenset({'Cheese'}) => frozenset({'Carrot', 'Bread'}) [0.42, 0.48]
frozenset({'Carrot'}) => frozenset({'Cheese', 'Bread'}) [0.40, 0.38]
frozenset({'Bread'}) => frozenset({'Cheese', 'Carrot'}) [0.39, 0.37]
frozenset({'HeavyCream', 'Bacon'}) => frozenset({'Bread'}) [0.39, 0.41]
frozenset({'HeavyCream', 'Bread'}) => frozenset({'Bacon'}) [0.40, 0.47]
frozenset({'Bacon', 'Bread'}) => frozenset({'HeavyCream'}) [0.38, 0.41]
frozenset({'HeavyCream'}) => frozenset({'Bacon', 'Bread'}) [0.38, 0.41]
frozenset({'Bacon'}) => frozenset({'HeavyCream', 'Bread'}) [0.40, 0.47]
frozenset({'Bread'}) => frozenset({'HeavyCream', 'Bacon'}) [0.39, 0.41]
frozenset({'Banana', 'Hazelnut'}) => frozenset({'Bread'}) [0.39, 0.36]
frozenset({'Banana', 'Bread'}) => frozenset({'Hazelnut'}) [0.40, 0.40]
frozenset({'Hazelnut', 'Bread'}) => frozenset({'Banana'}) [0.42, 0.50]
frozenset({'Banana'}) => frozenset({'Hazelnut', 'Bread'}) [0.42, 0.50]
frozenset({'Hazelnut'}) => frozenset({'Banana', 'Bread'}) [0.40, 0.40]
frozenset({'Bread'}) => frozenset({'Banana', 'Hazelnut'}) [0.39, 0.36]
frozenset({'Hazelnut', 'Bacon'}) => frozenset({'Bread'}) [0.37, 0.35]
frozenset({'Hazelnut', 'Bread'}) => frozenset({'Bacon'}) [0.40, 0.47]
frozenset({'Bacon', 'Bread'}) => frozenset({'Hazelnut'}) [0.39, 0.42]
frozenset({'Hazelnut'}) => frozenset({'Bacon', 'Bread'}) [0.39, 0.42]
frozenset({'Bacon'}) => frozenset({'Hazelnut', 'Bread'}) [0.40, 0.47]
frozenset({'Bread'}) => frozenset({'Hazelnut', 'Bacon'}) [0.37, 0.35]
frozenset({'Banana', 'Honey'}) => frozenset({'Bread'}) [0.39, 0.38]
frozenset({'Banana', 'Bread'}) => frozenset({'Honey'}) [0.39, 0.40]
frozenset({'Bread', 'Honey'}) => frozenset({'Banana'}) [0.40, 0.46]
frozenset({'Banana'}) => frozenset({'Bread', 'Honey'}) [0.40, 0.46]
frozenset({'Honey'}) => frozenset({'Banana', 'Bread'}) [0.39, 0.40]
frozenset({'Bread'}) => frozenset({'Banana', 'Honey'}) [0.39, 0.38]
frozenset({'Cheese', 'Honey'}) => frozenset({'Bread'}) [0.44, 0.38]
frozenset({'Bread', 'Honey'}) => frozenset({'Cheese'}) [0.45, 0.47]
frozenset({'Cheese', 'Bread'}) => frozenset({'Honey'}) [0.44, 0.40]
frozenset({'Honey'}) => frozenset({'Cheese', 'Bread'}) [0.44, 0.40]
frozenset({'Cheese'}) => frozenset({'Bread', 'Honey'}) [0.45, 0.47]
frozenset({'Bread'}) => frozenset({'Cheese', 'Honey'}) [0.44, 0.38]
frozenset({'Banana'}) => frozenset({'Apple'}) [0.52, 0.07]
frozenset({'Apple'}) => frozenset({'Banana'}) [0.52, 0.07]
frozenset({'HeavyCream'}) => frozenset({'Apple'}) [0.48, 0.02]
frozenset({'Apple'}) => frozenset({'HeavyCream'}) [0.48, 0.02]
frozenset({'Apple'}) => frozenset({'Carrot'}) [0.46, 0.01]
frozenset({'Carrot'}) => frozenset({'Apple'}) [0.46, 0.01]
frozenset({'Apple'}) => frozenset({'Bacon'}) [0.45, 0.04]
frozenset({'Bacon'}) => frozenset({'Apple'}) [0.45, 0.04]
frozenset({'Apple'}) => frozenset({'Bread'}) [0.43, 0.00]
frozenset({'Bread'}) => frozenset({'Apple'}) [0.43, 0.00]
frozenset({'Hazelnut'}) => frozenset({'Apple'}) [0.41, 0.02]
frozenset({'Apple'}) => frozenset({'Hazelnut'}) [0.41, 0.02]
frozenset({'Apple'}) => frozenset({'Honey'}) [0.46, 0.02]
frozenset({'Honey'}) => frozenset({'Apple'}) [0.46, 0.02]
frozenset({'Cheese'}) => frozenset({'Apple'}) [0.43, 0.06]
frozenset({'Apple'}) => frozenset({'Cheese'}) [0.43, 0.06]
frozenset({'Banana', 'HeavyCream'}) => frozenset({'Apple'}) [0.42, 0.43]
frozenset({'Banana', 'Apple'}) => frozenset({'HeavyCream'}) [0.38, 0.37]
frozenset({'HeavyCream', 'Apple'}) => frozenset({'Banana'}) [0.40, 0.47]
frozenset({'Banana'}) => frozenset({'HeavyCream', 'Apple'}) [0.40, 0.47]
frozenset({'HeavyCream'}) => frozenset({'Banana', 'Apple'}) [0.38, 0.37]
frozenset({'Apple'}) => frozenset({'Banana', 'HeavyCream'}) [0.42, 0.43]
frozenset({'Banana', 'Apple'}) => frozenset({'Carrot'}) [0.41, 0.38]
frozenset({'Banana', 'Carrot'}) => frozenset({'Apple'}) [0.41, 0.36]
frozenset({'Apple', 'Carrot'}) => frozenset({'Banana'}) [0.44, 0.50]
frozenset({'Banana'}) => frozenset({'Apple', 'Carrot'}) [0.44, 0.50]
frozenset({'Apple'}) => frozenset({'Banana', 'Carrot'}) [0.41, 0.36]
frozenset({'Carrot'}) => frozenset({'Banana', 'Apple'}) [0.41, 0.38]
frozenset({'Banana', 'Apple'}) => frozenset({'Bacon'}) [0.41, 0.40]
frozenset({'Banana', 'Bacon'}) => frozenset({'Apple'}) [0.40, 0.31]
frozenset({'Apple', 'Bacon'}) => frozenset({'Banana'}) [0.46, 0.51]
frozenset({'Banana'}) => frozenset({'Apple', 'Bacon'}) [0.46, 0.51]
frozenset({'Apple'}) => frozenset({'Banana', 'Bacon'}) [0.40, 0.31]
frozenset({'Bacon'}) => frozenset({'Banana', 'Apple'}) [0.41, 0.40]
frozenset({'Banana', 'Apple'}) => frozenset({'Bread'}) [0.38, 0.36]
frozenset({'Banana', 'Bread'}) => frozenset({'Apple'}) [0.39, 0.38]